/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'sk82_na_zd.xex'
*/

struct D3DVertexDeclaration;
struct rw::math::vpu::Matrix44;
struct rw::math::fpu::Vector3Template<float>;
struct renderengine::VertexDescriptor;
struct AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy>;
struct rw::collision::Volume;
struct rw::collision::Interval;
struct rw::collision::Feature;
struct rw::collision::GPInstance;
struct rw::collision::VolumeLineSegIntersectResult;
struct rw::collision::Volume::VTable;
struct rw::collision::Aggregate;
struct rw::collision::VolumeLineQuery;
struct rw::collision::VolumeBBoxQuery;
struct rw::collision::Aggregate::VTable;
struct rw::BitTable;
struct rw::physics::Inertia;
struct rw::physics::Material;
struct rw::physics::PartDefinition;
struct rw::physics::JointLimits;
struct rw::physics::JointFrames;
struct rw::physics::AssemblyDefinition::PartPair;
struct rw::physics::DriveDynamics;
struct rw::physics::DriveFrames;
struct rw::physics::AssemblyDefinition;
struct rw::physics::RigidBody;
struct rw::physics::Joint;
struct rw::physics::Drive;
struct rw::physics::Simulation;
struct rw::physics::RigidBodySimulationIslandMap;
struct rw::physics::SimulationWorkspace;
struct rw::physics::Part;
struct rw::physics::JointedPair;
struct rw::physics::DrivenPair;
struct rw::physics::Assembly;
struct renderengine::MeshHelper;
struct renderengine::IndexBuffer;
struct renderengine::VertexBuffer;
struct renderengine::DrawParameters;
struct renderengine::DrawIndexedParameters;
struct pegasus::tRBlendShapeData;
struct pegasus::tRMeshData::tBlendShapeInfo;
struct pegasus::tGrab;
struct pegasus::tVisualIndicator;
struct pegasus::tEmbeddedDataPtr;
struct pegasus::tEmbeddedData;
struct pegasus::tInstance;
struct pegasus::tSplineSegment;
struct pegasus::tWayPoint;
struct pegasus::tEmitterWayPointGroup;
struct pegasus::tEmitterWayPoint;

/* 2059 */
enum pegasus::tWorldPainterDictionaryData::eType : __int32
{
  eInvalid = 0xFFFFFFFF,
  eUInt32 = 0x0,
};

/* 2061 */
enum pegasus::tRAINPin::<unnamed_tag> : __int32
{
  eMaxNumOfLanes = 0x4,
};

/* 2097 */
enum pegasus::tCollisionBezier::<unnamed_tag> : __int32
{
  NUM_CONTROL_POINTS = 0x10,
};

/* 2166 */
enum pegasus::tStatsData::eStats : __int32
{
  eType = 0x0,
  eVersion = 0x1,
  eDiffuseCount = 0x2,
  eAmbientCount = 0x3,
  eNormalCount = 0x4,
  eSpecularCount = 0x5,
  eVertexCount = 0x6,
  eIndex16Count = 0x7,
  eIndex32Count = 0x8,
  eIndexBuffer16Count = 0x9,
  eIndexBuffer32Count = 0xA,
  eInstanceCount = 0xB,
  eRModelCount = 0xC,
  eRMeshCount = 0xD,
  eCModelCount = 0xE,
  eClusteredMeshCount = 0xF,
  eClusteredMeshClusterCount = 0x10,
  eClusteredMeshVertexCount = 0x11,
  eCollisionBezierCount = 0x12,
  eCollisionMapCount = 0x13,
  eBoxVolumeCount = 0x14,
  eClusteredMeshTriangleCount = 0x15,
  eRenderMeshTriangleCount = 0x16,
  eAIPathCount = 0x17,
  eRAINCount = 0x18,
  eLIONCount = 0x19,
  eNavMeshCount = 0x1A,
  eNavMesh2Count = 0x1B,
  eWorldPainterLayerCount = 0x1C,
  eWorldPainterQuadTreeCount = 0x1D,
  eWorldPainterDictionaryCount = 0x1E,
  eBlendShapeCount = 0x1F,
  eBlendShapeVertexCount = 0x20,
  eBlendShapeZeroDeltaCount = 0x21,
  eSplineCount = 0x22,
  eSplineHeaderCount = 0x23,
  eSplineSegmentCount = 0x24,
  eStatsCount = 0x25,
  eWayPointCount = 0x26,
  eDictionaryCount = 0x27,
  eMassiveCount = 0x28,
  eLocationCount = 0x29,
  eTableOfContentCount = 0x2A,
  eCollisionMaterialCount = 0x2B,
  eRenderMaterialCount = 0x2C,
  eEmitterWayPointCount = 0x2D,
  eSpatialMapCount = 0x2E,
  eAntiFrustumCount = 0x2F,
  eDiffuseSize = 0x30,
  eAmbientSize = 0x31,
  eNormalSize = 0x32,
  eSpecularSize = 0x33,
  eVertexBufferSize = 0x34,
  eIndexBuffer16Size = 0x35,
  eIndexBuffer32Size = 0x36,
  eInstanceSize = 0x37,
  eRModelSize = 0x38,
  eRMeshSize = 0x39,
  eCModelSize = 0x3A,
  eClusteredMeshSize = 0x3B,
  eCollisionBezierSize = 0x3C,
  eCollisionMapSize = 0x3D,
  eBoxVolumeSize = 0x3E,
  eAIPathSize = 0x3F,
  eRAINSize = 0x40,
  eLIONSize = 0x41,
  eNavMeshSize = 0x42,
  eNavMesh2Size = 0x43,
  eWorldPainterLayerSize = 0x44,
  eWorldPainterQuadTreeSize = 0x45,
  eWorldPainterDictionarySize = 0x46,
  eBlendShapeSize = 0x47,
  eBlendShapeVertexSize = 0x48,
  eBlendShapeZeroDeltaSize = 0x49,
  eSplineSize = 0x4A,
  eStatsSize = 0x4B,
  eWayPointSize = 0x4C,
  eDictionarySize = 0x4D,
  eMassiveSize = 0x4E,
  eLocationSize = 0x4F,
  eTableOfContentSize = 0x50,
  eCollisionMaterialSize = 0x51,
  eRenderMaterialSize = 0x52,
  eEmitterWayPointSize = 0x53,
  eSpatialMapSize = 0x54,
  eAntiFrustumSize = 0x55,
  eJunk = 0x56,
  eNumStats = 0x57,
  eStatsVersion = 0x9,
};

/* 2187 */
enum pegasus::tNavMesh2Data::eNeighbourTileDirection : __int32
{
  NTD_SELF = 0x0,
  NTD_NORTH = 0x1,
  NTD_SOUTH = 0x2,
  NTD_EAST = 0x3,
  NTD_WEST = 0x4,
  NTD_NUMNTDS = 0x5,
};

/* 2193 */
enum pegasus::tAntiFrustum::<unnamed_tag> : __int32
{
  NUM_ANTI_FRUSTUM_POINTS = 0x4,
};

/* 2228 */
enum pegasus::tMassiveData::tEntity::<unnamed_tag> : __int32
{
  eNumCoords = 0x4,
};

/* 2266 */
enum pegasus::tAudioMaterial::eSurface : __int32
{
  eSurface_Undefined = 0xFFFFFFFF,
  eSurface_NewAsphalt = 0x0,
  eSurface_OldAsphalt = 0x1,
  eSurface_SideWalk = 0x2,
  eSurface_Marble = 0x3,
  eSurface_Concrete_Park = 0x4,
  eSurface_Concrete_Pavers = 0x5,
  eSurface_Large_Tiles_Exterior = 0x6,
  eSurface_Brick = 0x7,
  eSurface_CobbleStone = 0x8,
  eSurface_Tile = 0x9,
  eSurface_Wood_Contest_Ramp = 0xA,
  eSurface_Wood_Plywood_DIY_Ramp = 0xB,
  eSurface_Dirt = 0xC,
  eSurface_Metal = 0xD,
  eSurface_Grass = 0xE,
  eSurface_Glass = 0xF,
  eSurface_Wood_Board_Walk = 0x10,
  eSurface_Materal_Grate = 0x11,
  eSurface_Deep_Snow = 0x12,
  eSurface_Packed_Snow = 0x13,
  eSurface_Ice = 0x14,
  eSurface_Count = 0x15,
};

/* 2267 */
enum pegasus::tAudioSurfaceType : __int32
{
  eAudioSurfaceType_Undefined = 0x0,
  eAudioSurfaceType_AsphaltSmooth = 0x1,
  eAudioSurfaceType_AsphaltRough = 0x2,
  eAudioSurfaceType_ConcretePolished = 0x3,
  eAudioSurfaceType_ConcreteRough = 0x4,
  eAudioSurfaceType_ConcreteAggregate = 0x5,
  eAudioSurfaceType_WoodRamp = 0x6,
  eAudioSurfaceType_Plywood = 0x7,
  eAudioSurfaceType_Dirt = 0x8,
  eAudioSurfaceType_Metal = 0x9,
  eAudioSurfaceType_Grass = 0xA,
  eAudioSurfaceType_MetalSolidRound1 = 0xB,
  eAudioSurfaceType_MetalSolidRound1Up = 0xC,
  eAudioSurfaceType_MetalSolidRound2 = 0xD,
  eAudioSurfaceType_MetalSolidSquare1 = 0xE,
  eAudioSurfaceType_MetalSolidSquare2 = 0xF,
  eAudioSurfaceType_MetalHollowRound1 = 0x10,
  eAudioSurfaceType_MetalHollowRound1Dead = 0x11,
  eAudioSurfaceType_MetalHollowRound1Dn = 0x12,
  eAudioSurfaceType_MetalHollowRound2 = 0x13,
  eAudioSurfaceType_MetalHollowRound2Dead = 0x14,
  eAudioSurfaceType_MetalHollowRound2Dn = 0x15,
  eAudioSurfaceType_MetalHollowRound3 = 0x16,
  eAudioSurfaceType_MetalHollowRound4 = 0x17,
  eAudioSurfaceType_MetalHollowSquare1 = 0x18,
  eAudioSurfaceType_MetalHollowSquare2 = 0x19,
  eAudioSurfaceType_MetalHollowSquare3 = 0x1A,
  eAudioSurfaceType_MetalHollowSquare3Dead = 0x1B,
  eAudioSurfaceType_MetalHollowSquare4 = 0x1C,
  eAudioSurfaceType_MetalHollow1 = 0x1D,
  eAudioSurfaceType_MetalHollow2 = 0x1E,
  eAudioSurfaceType_MetalSheet = 0x1F,
  eAudioSurfaceType_MetalComplex1 = 0x20,
  eAudioSurfaceType_MetalComplex2 = 0x21,
  eAudioSurfaceType_MetalComplex3 = 0x22,
  eAudioSurfaceType_MetalComplex4 = 0x23,
  eAudioSurfaceType_MetalComplex5 = 0x24,
  eAudioSurfaceType_MetalComplex6 = 0x25,
  eAudioSurfaceType_MetalComplex7 = 0x26,
  eAudioSurfaceType_MetalComplex8 = 0x27,
  eAudioSurfaceType_MetalComplexDebris = 0x28,
  eAudioSurfaceType_Wood1 = 0x29,
  eAudioSurfaceType_Wood1Up = 0x2A,
  eAudioSurfaceType_Wood2 = 0x2B,
  eAudioSurfaceType_Wood3 = 0x2C,
  eAudioSurfaceType_Wood3Up = 0x2D,
  eAudioSurfaceType_Wood4 = 0x2E,
  eAudioSurfaceType_Plastic1 = 0x2F,
  eAudioSurfaceType_Plastic2 = 0x30,
  eAudioSurfaceType_Plastic3 = 0x31,
  eAudioSurfaceType_Plastic4 = 0x32,
  eAudioSurfaceType_GlassThickLarge = 0x33,
  eAudioSurfaceType_GlassThinSmall = 0x34,
  eAudioSurfaceType_ConcreteCurb = 0x35,
  eAudioSurfaceType_ConcreteBench = 0x36,
  eAudioSurfaceType_Leaves = 0x37,
  eAudioSurfaceType_Bush = 0x38,
  eAudioSurfaceType_Pottery = 0x39,
  eAudioSurfaceType_Paper = 0x3A,
  eAudioSurfaceType_Cardboard = 0x3B,
  eAudioSurfaceType_GarbageBag = 0x3C,
  eAudioSurfaceType_GarbageSpill = 0x3D,
  eAudioSurfaceType_Bottle = 0x3E,
  eAudioSurfaceType_TileCeramic = 0x3F,
  eAudioSurfaceType_MarbleOrSlate = 0x40,
  eAudioSurfaceType_BrickSmooth = 0x41,
  eAudioSurfaceType_BrickCoarse = 0x42,
  eAudioSurfaceType_ManholeMetal = 0x43,
  eAudioSurfaceType_MetalGrateSewer = 0x44,
  eAudioSurfaceType_MetalGratePlanter = 0x45,
  eAudioSurfaceType_DeepSnow = 0x46,
  eAudioSurfaceType_PackedSnow = 0x47,
  eAudioSurfaceType_Ice = 0x48,
  eAudioSurfaceType_Antennas = 0x49,
  eAudioSurfaceType_Chandelier = 0x4A,
  eAudioSurfaceType_PlexiglassSmall = 0x4B,
  eAudioSurfaceType_PlexiglassLarge = 0x4C,
  eAudioSurfaceType_PottedPlant = 0x4D,
  eAudioSurfaceType_CrumpledPaper = 0x4E,
  eAudioSurfaceType_Cloth = 0x4F,
  eAudioSurfaceType_PopCan = 0x50,
  eAudioSurfaceType_PaperCup = 0x51,
  eAudioSurfaceType_WireCable = 0x52,
  eAudioSurfaceType_VolleyBall = 0x53,
  eAudioSurfaceType_OilDrum = 0x54,
  eAudioSurfaceType_DMORail = 0x55,
  eAudioSurfaceType_Fruit = 0x56,
  eAudioSurfaceType_PlasticBottle = 0x57,
  eAudioSurfaceType_DrumPylon = 0x58,
  eAudioSurfaceType_MetalRail4 = 0x59,
  eAudioSurfaceType_Wood5 = 0x5A,
  eAudioSurfaceType_MetalRamp = 0x5B,
  eAudioSurfaceType_ComplexPlastic1 = 0x5C,
  kAudioSurfaceTypeCount = 0x5D,
};

/* 2268 */
enum pegasus::tPhysicsSurfaceType : __int32
{
  ePhysicsSurfaceType_Undefined = 0x0,
  ePhysicsSurfaceType_Smooth = 0x1,
  ePhysicsSurfaceType_Rough = 0x2,
  ePhysicsSurfaceType_Slow = 0x3,
  ePhysicsSurfaceType_Slippery = 0x4,
  ePhysicsSurfaceType_VerySlow = 0x5,
  ePhysicsSurfaceType_Unrideable = 0x6,
  ePhysicsSurfaceType_DoNotAlign = 0x7,
  ePhysicsSurfaceType_Stair = 0x8,
  ePhysicsSurfaceType_Wipeout = 0x9,
  kPhysicsSurfaceTypeCount = 0xA,
};

/* 2269 */
enum pegasus::tSurfacePatternType : __int32
{
  eSurfacePatternType_None = 0x0,
  eSurfacePatternType_SpiderCrack = 0x1,
  eSurfacePatternType_Square2x2 = 0x2,
  eSurfacePatternType_Square4x4 = 0x3,
  eSurfacePatternType_Square8x8 = 0x4,
  eSurfacePatternType_Square12x12 = 0x5,
  eSurfacePatternType_Square24x24 = 0x6,
  eSurfacePatternType_IrregularSmall = 0x7,
  eSurfacePatternType_IrregularMedium = 0x8,
  eSurfacePatternType_IrregularLarge = 0x9,
  eSurfacePatternType_Slats = 0xA,
  eSurfacePatternType_Sidewalk = 0xB,
  eSurfacePatternType_BrickTileRandomSize = 0xC,
  eSurfacePatternType_MiniTile = 0xD,
  eSurfacePatternType_Special1 = 0xE,
  eSurfacePatternType_Special2 = 0xF,
  kSurfacePatternTypeCount = 0x10,
};

/* 2271 */
enum pegasus::tHotPoint::TYPE::<unnamed_tag> : __int32
{
  eHand = 0x0,
  eLeftHand = 0x1,
  eRightHand = 0x2,
  eFoot = 0x3,
  eLeftFoot = 0x4,
  eRightFoot = 0x5,
  eSit = 0x6,
  eEmitter = 0x7,
  eUndefined = 0x8,
};

/* 2272 */
enum pegasus::tVisualIndicator::<unnamed_tag> : __int32
{
  kBillboard = 0x1,
  kOpenForm = 0x2,
  kClosedForm = 0x4,
  kPeriodicForm = 0x8,
};

/* 2273 */
enum pegasus::tGrab::<unnamed_tag> : __int32
{
  kHandle = 0x1,
  kVerticalHandle = 0x2,
  kEdge = 0x4,
  kVerticalEdge = 0x8,
  kFlat = 0x10,
  kNoPushing = 0x20,
  kNoPulling = 0x40,
  kVertical = 0x80,
  kOneHand = 0x100,
  kFixHandsAtEndPoints = 0x200,
};

/* 2274 */
enum pegasus::tMassiveData::tEntity::tRotationType : __int32
{
  Rotation_Undefined = 0xFFFFFFFF,
  Rotation_None = 0x0,
  Rotation_Any = 0x1,
  Rotation_LineOfSight = 0x2,
};

/* 2275 */
enum pegasus::tRAINIntersection::<unnamed_tag> : __int32
{
  eMaxPassages = 0x40,
};

/* 2276 */
enum pegasus::eRAINItemType : __int32
{
  RIT_INTERSECTION = 0x0,
  RIT_ROAD = 0x1,
  RIT_NUMRITS = 0x2,
};

/* 2277 */
enum pegasus::tRAINCurve::<unnamed_tag> : __int32
{
  ePrecision = 0x10,
};

/* 2278 */
enum pegasus::tRAINSuperRoad::eFlags : __int32
{
  eParkingLane = 0x1,
  eLaneChanging = 0x2,
};

/* 2279 */
enum pegasus::tAIPathNode::eFlags : __int32
{
  bIsBoardFlipped = 0x1,
  bIsCrouched = 0x2,
  bIsAirborne = 0x4,
  bIsOffBoard = 0x8,
  bBitFlag5 = 0x10,
  bBitFlag6 = 0x20,
  bBitFlag7 = 0x40,
  bBitFlag8 = 0x80,
};

/* 2280 */
typedef pegasus::tAIPathNode::eFlags pegasus::tAIPathNodeExtData::eFlags;

/* 2281 */
enum pegasus::tAIPath::ESkillLevel : __int32
{
  eSkillLevel_Invalid = 0xFFFFFFFF,
  eSkillLevel_Easy = 0x0,
  eSkillLevel_Medium = 0x1,
  eSkillLevel_Hard = 0x2,
  eSkillLevel_VeryHard = 0x3,
  eSkillLevel_Extreme = 0x4,
  eSkillLevel_Max = 0x5,
};

/* 2306 */
enum pegasus::tRMaterial::tFlags : __int32
{
  kNone = 0x0,
  kCPUSkinning = 0x1,
  kScalarConstant = 0x2,
};

/* 3123 */
enum pegasus::NavMesh2::eCellDir : __int32
{
  CD_SELF = 0x0,
  CD_NORTH = 0x1,
  CD_SOUTH = 0x2,
  CD_EAST = 0x3,
  CD_WEST = 0x4,
  CD_NUMCDS = 0x5,
  CD_INVALID = 0x7,
};

/* 5331 */
enum pegasus::eTriggerInstanceType : __int32
{
  eTriggerInstanceType_Challenge = 0x0,
  eTriggerInstanceType_Stairs = 0x1,
  eTriggerInstanceType_Camera = 0x2,
  eTriggerInstanceType_Crowd = 0x3,
};

/* 5902 */
enum pegasus::tVersionData::Version : __int32
{
  VERSION = 0x19,
  REVISION = 0x2,
};

/* 6746 */
enum pegasus::NavMesh2::eCellIndex : __int32
{
  CI_INVALID = 0x1FFFFFFF,
};

/* 6866 */
struct $91D1B2149FAC90180ECB9AC277F76009
{
  float x;
  float y;
  float z;
  float w;
};

/* 6867 */
union $B7B8F02308E65255310DBC0B27D2928D
{
  $91D1B2149FAC90180ECB9AC277F76009 __s0;
  float v[4];
  unsigned int u[4];
};

/* 6868 */
struct __vector4
{
  $B7B8F02308E65255310DBC0B27D2928D ___u0;
};

/* 15138 */
struct __cppobj rw::math::vpu::Vector4
{
  __vector4 mV;
};

/* 16804 */
struct __cppobj pegasus::tAABB
{
  rw::math::vpu::Vector4 m_Min;
  rw::math::vpu::Vector4 m_Max;
};

/* 16805 */
struct pegasus::tAttribPair
{
  unsigned __int64 m_ClassKey;
  unsigned __int64 m_InstanceKey;
};

/* 16826 */
struct __cppobj pegasus::tSimpleTriMeshData
{
  unsigned int m_uiNumVertexPositions;
  unsigned int m_uiNumVertexNormals;
  unsigned int m_uiNumVertexIndices;
  rw::math::fpu::Vector3Template<float> *m_pVertexPositions;
  rw::math::fpu::Vector3Template<float> *m_pVertexNormals;
  unsigned int *m_pVertexIndices;
};

/* 15611 */
struct __cppobj rw::math::fpu::Vector3Template<float>
{
  float x;
  float y;
  float z;
};

/* 16827 */
union pegasus::tCModelData::tCollisionMesh
{
  rw::collision::Volume *m_pVolume;
  pegasus::tSimpleTriMeshData *m_pSimpleTriMesh;
};

/* 15011 */
struct __cppobj rw::math::vpu::Vector3
{
  __vector4 mV;
};

/* 15012 */
struct __cppobj rw::math::vpu::Matrix44Affine
{
  rw::math::vpu::Vector3 xAxis;
  rw::math::vpu::Vector3 yAxis;
  rw::math::vpu::Vector3 zAxis;
  rw::math::vpu::Vector3 wAxis;
};

/* 16819 */
struct rw::collision::AggregateSpecificData
{
  rw::collision::Aggregate *agg;
};

/* 16820 */
struct rw::collision::SphereSpecificData
{
  void *nothing;
};

/* 16821 */
struct rw::collision::CapsuleSpecificData
{
  float hh;
};

/* 16822 */
struct rw::collision::TriangleSpecificData
{
  float edgeCos0;
  float edgeCos1;
  float edgeCos2;
};

/* 16823 */
struct rw::collision::BoxSpecificData
{
  float hx;
  float hy;
  float hz;
};

/* 16824 */
struct rw::collision::CylinderSpecificData
{
  float hh;
  float innerRadius;
};

/* 16825 */
union $877A47AA15D4BD367D845A958F733A2C
{
  rw::collision::AggregateSpecificData aggregateData;
  rw::collision::SphereSpecificData sphereData;
  rw::collision::CapsuleSpecificData capsuleData;
  rw::collision::TriangleSpecificData triangleData;
  rw::collision::BoxSpecificData boxData;
  rw::collision::CylinderSpecificData cylinderData;
  unsigned int sizeOfTargetPointer[2];
};

/* 16806 */
struct __cppobj rw::collision::Volume
{
  rw::math::vpu::Matrix44Affine transform;
  rw::collision::Volume::VTable *vTable;
  $877A47AA15D4BD367D845A958F733A2C ___u2;
  float radius;
  unsigned int groupID;
  unsigned int surfaceID;
  unsigned int m_flags;
};

/* 2131 */
enum rw::collision::VolumeType : __int32
{
  VOLUMETYPENULL = 0x0,
  VOLUMETYPESPHERE = 0x1,
  VOLUMETYPECAPSULE = 0x2,
  VOLUMETYPETRIANGLE = 0x3,
  VOLUMETYPEBOX = 0x4,
  VOLUMETYPECYLINDER = 0x5,
  VOLUMETYPEAGGREGATE = 0x6,
  VOLUMETYPENUMINTERNALTYPES = 0x7,
  VOLUMETYPEFORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 16814 */
struct rw::collision::Volume::VTable
{
  rw::collision::VolumeType typeID;
  unsigned int (__cdecl *getBBox)(rw::collision::Volume *this, const rw::math::vpu::Matrix44Affine *, unsigned int, AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> *);
  rw::math::vpu::Vector3 *(__cdecl *getBBoxDiag)(rw::collision::Volume *this, rw::math::vpu::Vector3 *result);
  unsigned int (__cdecl *getInterval)(rw::collision::Volume *this, const rw::math::vpu::Vector3 *, rw::collision::Interval *);
  unsigned int (__cdecl *getMaximumFeature)(rw::collision::Volume *this, unsigned int, const rw::math::vpu::Vector3 *, rw::collision::Feature *);
  unsigned int (__cdecl *createGPInstance)(rw::collision::Volume *this, rw::collision::GPInstance *, const rw::math::vpu::Matrix44Affine *);
  unsigned int (__cdecl *lineSegIntersect)(rw::collision::Volume *this, const rw::math::vpu::Vector3 *, const rw::math::vpu::Vector3 *, const rw::math::vpu::Matrix44Affine *, rw::collision::VolumeLineSegIntersectResult *, const float);
  void (__cdecl *release)(rw::collision::Volume *this);
  const char *name;
  unsigned int flags;
};

/* 16803 */
const struct __cppobj AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy>
{
  rw::math::vpu::Vector3 m_min;
  rw::math::vpu::Vector3 m_max;
};

/* 16815 */
struct __cppobj rw::collision::Aggregate
{
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_AABB;
  rw::collision::Aggregate::VTable *m_vTable;
  unsigned int m_numTagBits;
  unsigned int m_numVolumes;
  unsigned int pad;
};

/* 15125 */
struct __cppobj rw::math::vpu::VecFloat
{
  __vector4 mV;
};

/* 16807 */
struct __cppobj __declspec(align(16)) rw::collision::Interval
{
  rw::math::vpu::VecFloat min;
  rw::math::vpu::VecFloat max;
  float padding[2];
};

/* 16808 */
struct __cppobj rw::collision::FeatureEdge
{
  rw::math::vpu::Vector3 base;
  rw::math::vpu::Vector3 dir;
  rw::math::vpu::Vector3 pn;
  rw::math::vpu::VecFloat length;
};

/* 16809 */
struct __cppobj rw::collision::Feature
{
  unsigned int region;
  __declspec(align(16)) rw::collision::FeatureEdge edges[8];
  rw::math::vpu::Vector3 ownNormal;
  rw::math::vpu::Vector3 pt;
  int numedges;
};

/* 2184 */
enum rw::collision::GPInstance::VolumeType : __int32
{
  UNUSED = 0x0,
  SPHERE = 0x1,
  CAPSULE = 0x2,
  TRIANGLE = 0x3,
  BOX = 0x4,
  CYLINDER = 0x5,
  NUMINTERNALTYPES = 0x6,
  FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 16811 */
struct rw::collision::GPInstance::VolumeMethods
{
  void (__cdecl *mGetMaximumFeature)(rw::collision::GPInstance *this, unsigned int, const rw::math::vpu::Vector3 *, rw::collision::Feature *);
  void (__cdecl *mGetInterval)(rw::collision::GPInstance *this, const rw::math::vpu::Vector3 *, rw::collision::Interval *);
  void (__cdecl *mGetIntervals)(rw::collision::GPInstance *this, const rw::math::vpu::Vector3 *, unsigned int, rw::collision::Interval *);
  void (__cdecl *mGetBBox)(rw::collision::GPInstance *this, AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> *);
};

/* 16810 */
struct __cppobj __declspec(align(16)) rw::collision::GPInstance
{
  rw::math::vpu::Vector3 mPos;
  rw::math::vpu::Vector3 mFaceNormals[3];
  rw::math::vpu::Vector3 mEdgeDirections[3];
  rw::math::vpu::Vector3 mDimensions;
  float mFatness;
  unsigned int mVolumeTag;
  unsigned int mUserTag;
  unsigned __int8 mNumFaceNormals;
  unsigned __int8 mNumEdgeDirections;
  rw::collision::GPInstance::VolumeType mVolumeType;
  unsigned int mFlags;
  float mEdgeData[3];
  rw::collision::GPInstance::VolumeMethods mVolumeMethods;
};

/* 16812 */
struct __cppobj rw::collision::VolRef
{
  const rw::collision::Volume *volume;
  rw::math::vpu::Matrix44Affine *tm;
  __declspec(align(16)) rw::math::vpu::Matrix44Affine tmContents;
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> bBox;
  unsigned int tag;
  unsigned __int8 numTagBits;
};

/* 16813 */
struct __cppobj rw::collision::VolumeLineSegIntersectResult
{
  const rw::collision::Volume *v;
  __declspec(align(16)) rw::math::vpu::Vector3 position;
  rw::math::vpu::Vector3 normal;
  rw::math::vpu::Vector3 volParam;
  float lineParam;
  rw::collision::VolRef vRef;
};

/* 2058 */
enum rw::collision::ObjectType : __int32
{
  RWCOBJECTTYPE_NA = 0x80000,
  RWCOBJECTTYPE_VOLUME = 0x80001,
  RWCOBJECTTYPE_SIMPLEMAPPEDARRAY = 0x80002,
  RWCOBJECTTYPE_TRIANGLEKDTREEPROCEDURAL = 0x80003,
  RWCOBJECTTYPE_KDTREEMAPPEDARRAY = 0x80004,
  RWCOBJECTTYPE_BBOX = 0x80005,
  RWCOBJECTTYPE_CLUSTEREDMESH = 0x80006,
  RWCOBJECTTYPE_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 16818 */
struct rw::collision::Aggregate::VTable
{
  rw::collision::ObjectType m_type;
  unsigned int (__cdecl *m_GetSize)(rw::collision::Aggregate *this);
  unsigned int m_alignment;
  unsigned int m_isProcedural;
  void (__cdecl *m_Update)(rw::collision::Aggregate *this);
  unsigned int (__cdecl *m_LineIntersectionQuery)(rw::collision::Aggregate *this, rw::collision::VolumeLineQuery *, const rw::math::vpu::Matrix44Affine *);
  unsigned int (__cdecl *m_BBoxOverlapQuery)(rw::collision::Aggregate *this, rw::collision::VolumeBBoxQuery *, const rw::math::vpu::Matrix44Affine *);
};

/* 2083 */
enum rw::collision::VolumeLineQuery::QueryResultsSet : __int32
{
  ALLLINEINTERSECTIONS = 0x0,
  ANYLINEINTERSECTION = 0x1,
  NEARESTLINEINTERSECTION = 0x2,
};

/* 16816 */
struct __cppobj __declspec(align(8)) rw::collision::VolumeLineQuery
{
  const rw::collision::Volume **m_inputVols;
  const rw::math::vpu::Matrix44Affine **m_inputMats;
  unsigned int m_numInputs;
  unsigned int m_currInput;
  rw::collision::VolumeLineSegIntersectResult *m_resBuffer;
  unsigned int m_resCount;
  unsigned int m_resMax;
  unsigned int m_resBufferSize;
  rw::math::vpu::Vector3 m_pt1;
  rw::math::vpu::Vector3 m_pt2;
  float m_fatness;
  rw::collision::VolRef *m_stackVRefBuffer;
  rw::collision::VolRef m_currVRef;
  unsigned int m_stackNext;
  unsigned int m_stackMax;
  rw::collision::VolRef *m_primVRefBuffer;
  unsigned int m_primNext;
  unsigned int m_primBufferSize;
  rw::collision::Volume *m_instVolPool;
  unsigned int m_instVolCount;
  unsigned int m_instVolMax;
  unsigned int m_aggIndex;
  void *m_spatialMapQueryMem;
  void *m_curSpatialMapQuery;
  float m_endClipVal;
  rw::collision::VolumeLineQuery::QueryResultsSet m_resultsSet;
  unsigned int m_tag;
  unsigned __int8 m_numTagBits;
};

/* 16817 */
struct __cppobj __declspec(align(16)) rw::collision::VolumeBBoxQuery
{
  const rw::collision::Volume **m_inputVols;
  const rw::math::vpu::Matrix44Affine **m_inputMats;
  unsigned int m_numInputs;
  unsigned int m_currInput;
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_aabb;
  rw::collision::VolRef *m_stackVRefBuffer;
  rw::collision::VolRef m_currVRef;
  unsigned int m_stackNext;
  unsigned int m_stackMax;
  rw::collision::VolRef *m_primVRefBuffer;
  unsigned int m_primNext;
  unsigned int m_primBufferSize;
  rw::collision::Volume *m_instVolPool;
  unsigned int m_instVolCount;
  unsigned int m_instVolMax;
  unsigned int m_aggIndex;
  void *m_spatialMapQueryMem;
  void *m_curSpatialMapQuery;
  unsigned int m_tag;
  unsigned __int8 m_numTagBits;
};

/* 16828 */
union pegasus::tStringPtr
{
  unsigned int Offset;
  unsigned __int8 *Pointer;
};

/* 16829 */
struct pegasus::tCModelData::tMeshData
{
  pegasus::tCModelData::tCollisionMesh m_Mesh;
  pegasus::tStringPtr m_BoneName;
};

/* 16851 */
union $DD984FAA73881FAC8712DDF5DE760971
{
  pegasus::tCModelData::tMeshData *m_pMeshTable;
  rw::physics::Assembly *m_pAssembly;
};

/* 16852 */
struct __cppobj pegasus::tCModelData
{
  pegasus::tCModelData::tCollisionMesh m_BoundingVolume;
  unsigned int m_iNumMeshes;
  $DD984FAA73881FAC8712DDF5DE760971 ___u2;
};

/* 16850 */
struct __cppobj rw::physics::Assembly
{
  const rw::BitTable *m_cullingTable;
  const rw::physics::AssemblyDefinition *m_definition;
  rw::physics::Part *m_partList;
  rw::physics::JointedPair *m_jointList;
  rw::physics::DrivenPair *m_driveList;
  unsigned int m_worldIndex;
  unsigned int m_groupID;
  unsigned int m_numParts;
  unsigned int m_numJoints;
  unsigned int m_numDrives;
  void *m_userData;
  unsigned __int16 m_flags;
  unsigned __int16 m_userFlags;
};

/* 16830 */
const struct __cppobj rw::BitTable
{
  unsigned int m_rows;
  unsigned int m_columns;
  unsigned int m_arraySize;
  unsigned int m_array[1];
};

/* 16840 */
const struct __cppobj rw::physics::AssemblyDefinition
{
  rw::physics::PartDefinition *m_partDef;
  unsigned int m_numParts;
  unsigned int m_numJoints;
  rw::physics::JointLimits *m_jointLimits;
  rw::physics::JointFrames *m_jointFrames;
  rw::physics::AssemblyDefinition::PartPair *m_jointParts;
  unsigned int m_numDrives;
  rw::physics::DriveDynamics *m_driveDynamics;
  rw::physics::DriveFrames *m_driveFrames;
  rw::physics::AssemblyDefinition::PartPair *m_driveParts;
  rw::BitTable *m_cullingTable;
  unsigned int *m_hashedPartNames;
};

/* 16847 */
struct __cppobj rw::physics::Part
{
  rw::math::vpu::Matrix44Affine m_partTM;
  const rw::collision::Volume *m_volume;
  const rw::math::vpu::Matrix44Affine *m_inverseBodyLTM;
  const rw::physics::Inertia *m_inertia;
  rw::physics::RigidBody *m_body;
  const rw::physics::Material *m_material;
  unsigned int m_worldIndex;
  unsigned __int16 m_internalFlags;
  unsigned __int16 m_userFlags;
  void *m_userData;
};

/* 16848 */
struct __cppobj rw::physics::JointedPair
{
  rw::physics::Part *m_parent;
  rw::physics::Part *m_child;
  rw::physics::JointFrames *m_frames;
  rw::physics::JointLimits *m_limits;
  rw::physics::Joint *m_joint;
};

/* 15582 */
struct __cppobj rw::math::vpu::Quaternion
{
  __vector4 mV;
};

/* 16839 */
struct __cppobj rw::physics::DriveFrames
{
  rw::math::vpu::Quaternion mQuatA;
  rw::math::vpu::Vector3 mPosA;
  rw::math::vpu::Quaternion mQuatB;
  rw::math::vpu::Vector3 mPosB;
};

/* 2456 */
enum rw::physics::DriveType : __int32
{
  NO_DRIVE = 0x0,
  SOFT_DRIVE = 0x1,
  HARD_DRIVE = 0x2,
  DRIVE_FORCE_ENUM_SIZE = 0x7FFFFFFF,
};

/* 16837 */
struct __cppobj rw::physics::DriveDynamics::Params
{
  float mSpring;
  float mDamping;
  float mStrength;
  rw::physics::DriveType mType;
};

/* 16838 */
struct __cppobj rw::physics::DriveDynamics
{
  rw::physics::DriveDynamics::Params mLinear;
  rw::physics::DriveDynamics::Params mAngular;
};

/* 16849 */
struct __cppobj rw::physics::DrivenPair
{
  rw::physics::Part *m_parent;
  rw::physics::Part *m_child;
  __declspec(align(16)) rw::physics::DriveFrames m_frames;
  rw::physics::DriveDynamics m_dynamics;
  rw::physics::Drive *m_drive;
};

/* 16831 */
struct __cppobj __declspec(align(16)) rw::physics::Inertia
{
  rw::math::vpu::Vector3 mInvTens;
  float mInvMass;
  float mSpherical;
  float mMaxVelocity;
  float mMaxOmega;
  float mLinearDrag;
  float mAngularDrag;
};

/* 16832 */
struct __cppobj rw::physics::Material
{
  float m_mus;
  float m_mud;
  float m_res;
};

/* 16833 */
struct __cppobj __declspec(align(16)) rw::physics::PartDefinition
{
  rw::collision::Volume *m_volume;
  rw::physics::Inertia m_inertia;
  rw::math::vpu::Matrix44Affine m_inverseBodyLTM;
  rw::physics::Material m_material;
  unsigned int m_hasInverseBodyLTM;
  unsigned int m_isStaticBody;
};

/* 2389 */
enum rw::physics::SwingType : __int32
{
  SWING_LOCKED = 0x0,
  SWING_CONE = 0x1,
  SWING_HINGE = 0x2,
  SWING_AXLE = 0x3,
  SWING_FREE = 0x4,
  SWING_FORCE_ENUM_SIZE = 0x7FFFFFFF,
};

/* 2396 */
enum rw::physics::TwistType : __int32
{
  TWIST_LOCKED = 0x0,
  TWIST_ARC = 0x1,
  TWIST_FREE = 0x2,
  TWIST_FORCE_ENUM_SIZE = 0x7FFFFFFF,
};

/* 16834 */
struct __cppobj rw::physics::JointLimits
{
  rw::math::vpu::Vector3 mPprism;
  rw::math::vpu::Vector3 mVprism;
  float mVtwist;
  float mVswing;
  float mSwinga;
  float mTwista;
  float mSwingc;
  float mTwistc;
  rw::physics::SwingType mSwingf;
  rw::physics::TwistType mTwistf;
};

/* 16835 */
struct __cppobj rw::physics::JointFrames
{
  rw::math::vpu::Quaternion mQuatA;
  rw::math::vpu::Vector3 mPosA;
  rw::math::vpu::Quaternion mQuatB;
  rw::math::vpu::Vector3 mPosB;
  rw::math::vpu::Quaternion mQuatL;
};

/* 16836 */
struct __cppobj rw::physics::AssemblyDefinition::PartPair
{
  int m_parentIndex;
  int m_childIndex;
};

/* 2526 */
enum rw::physics::BodyState : __int32
{
  FREE_BODY = 0x0,
  STATIC_BODY = 0x1,
  FROZEN_BODY = 0x2,
  ACTIVE_BODY = 0x4,
  STATE_FILTER = 0x7,
  SPY_BODY = 0x8,
  BS_FORCE_ENUM_SIZE = 0x7FFFFFFF,
};

/* 16841 */
struct __cppobj rw::physics::RigidBody
{
  rw::math::vpu::Quaternion mQuat;
  rw::math::fpu::Vector3Template<float> mCom;
  unsigned int mId;
  rw::math::fpu::Vector3Template<float> mVel;
  int mRight;
  rw::math::fpu::Vector3Template<float> mOmega;
  int mLeft;
  rw::math::fpu::Vector3Template<float> mRi;
  rw::physics::Simulation *mStasis;
  rw::math::fpu::Vector3Template<float> mUp;
  rw::physics::Inertia *mInertia;
  rw::math::fpu::Vector3Template<float> mAt;
  unsigned int mTag;
  rw::math::fpu::Vector3Template<float> mIfull;
  float mInvm;
  rw::math::fpu::Vector3Template<float> mIsplt;
  rw::physics::BodyState mState;
  rw::math::fpu::Vector3Template<float> mForce;
  float mKine;
  rw::math::fpu::Vector3Template<float> mTorque;
  unsigned int mCool;
};

/* 16842 */
struct __cppobj rw::physics::Joint
{
  rw::physics::JointFrames *m_skel;
  rw::physics::JointLimits *m_limit;
  int m_right;
  int m_left;
  int m_bodyA;
  int m_bodyB;
  unsigned int m_tag;
  unsigned int m_spy;
};

/* 16843 */
struct __cppobj rw::physics::Drive
{
  rw::physics::DriveFrames *m_skel;
  rw::physics::DriveDynamics *m_crtl;
  int m_right;
  int m_left;
  int m_bodyA;
  int m_bodyB;
  unsigned int m_tag;
  unsigned int m_spy;
};

/* 2390 */
enum rw::physics::SpyingFlag : __int32
{
  SPY_NOTHING = 0x0,
  SPY_JOINTS = 0x1,
  SPY_DRIVES = 0x2,
  SPY_CONTACTS = 0x4,
  SPY_FORCE_ENUM_SIZE = 0x7FFFFFFF,
};

/* 16844 */
struct __cppobj rw::physics::Simulation
{
  rw::physics::RigidBody *m_RB_Stack;
  rw::physics::Joint *m_JT_Stack;
  rw::physics::Drive *m_DR_Stack;
  void *m_RF_Stack;
  void *m_CJ_Stack;
  void *m_JJ_Stack;
  void *m_DJ_Stack;
  rw::physics::RigidBody *m_FreeRB_Anchor;
  rw::physics::RigidBody *m_StaticRB_Anchor;
  rw::physics::RigidBody *m_FrozenRB_Anchor;
  rw::physics::RigidBody *m_ActiveRB_Anchor;
  rw::physics::Joint *m_FreeJT_Anchor;
  rw::physics::Joint *m_ActiveJT_Anchor;
  rw::physics::Drive *m_FreeDR_Anchor;
  rw::physics::Drive *m_ActiveDR_Anchor;
  unsigned int m_FreeRB_Count;
  unsigned int m_StaticRB_Count;
  unsigned int m_FrozenRB_Count;
  unsigned int m_ActiveRB_Count;
  unsigned int m_FreeJT_Count;
  unsigned int m_ActiveJT_Count;
  unsigned int m_FreeDR_Count;
  unsigned int m_ActiveDR_Count;
  unsigned int m_JT_Stride;
  unsigned int m_DR_Stride;
  volatile unsigned int m_CT_Count;
  unsigned int m_CS_Count;
  unsigned int m_JT_Count;
  unsigned int m_JS_Count;
  unsigned int m_DR_Count;
  unsigned int m_DS_Count;
  unsigned int m_CT_Max;
  unsigned int m_JT_Max;
  unsigned int m_DR_Max;
  unsigned int m_RF_Max;
  __declspec(align(8)) rw::math::vpu::Vector3 m_Gravity;
  float m_TimeStep;
  float m_Frequency;
  unsigned int m_CoolDown;
  float m_MinEnergy;
  unsigned int m_MaxIteration;
  rw::physics::SpyingFlag m_SpyFlag;
  bool m_simulationIslandsEnabled;
  const rw::physics::RigidBodySimulationIslandMap *m_RB_Islands;
  unsigned int m_islandRigidBodiesCount[10];
  unsigned int m_islandContactsCount[10];
  unsigned int m_islandJointsCount[10];
  unsigned int m_islandDrivesCount[10];
  void *m_islandRigidBodies[10];
  void *m_islandContacts[10];
  void *m_islandJoints[10];
  void *m_islandDrives[10];
  void *m_islandContactJacobians[10];
  void *m_islandJointJacobians[10];
  void *m_islandDriveJacobians[10];
  void *m_islandCJStack[10];
  void *m_islandJJStack[10];
  void *m_islandDJStack[10];
  void *m_CJ_Stack_Islands;
  unsigned int m_simulationSize;
  unsigned int m_workspaceSize;
  const rw::physics::SimulationWorkspace *m_workspace;
};

/* 16845 */
const struct __cppobj rw::physics::RigidBodySimulationIslandMap
{
  const rw::physics::Simulation *m_simulation;
  char *m_islands;
};

/* 16846 */
const struct __cppobj rw::physics::SimulationWorkspace
{
};

/* 16853 */
const struct __cppobj pegasus::tTriggerInstance
{
  rw::math::vpu::Matrix44Affine m_TransformMatrix;
  pegasus::tAABB m_BBox;
  rw::math::vpu::Vector3 m_BasePlaneNormal;
  rw::math::vpu::Vector3 m_BasePlaneLeadingEdge[2];
  rw::math::vpu::Vector3 m_BasePlaneTrailingEdge[2];
  unsigned __int64 m_uiGuid;
  unsigned __int64 m_uiGuidLocal;
  pegasus::tAttribPair m_AttribKey;
  unsigned __int64 m_TriggerData;
  unsigned int m_TriggerType;
  pegasus::tCModelData *m_pCModel;
  pegasus::tStringPtr m_Name;
  unsigned __int8 m_PadBuffer[12];
};

/* 2075 */
enum RwObjectType : __int32
{
  RWOBJECTTYPE_NULL = 0x0,
  RWOBJECTTYPE_NA = 0x10000,
  RWOBJECTTYPE_ARENA = 0x10001,
  RWOBJECTTYPE_RAW = 0x10002,
  RWOBJECTTYPE_SUBREFERENCE = 0x10003,
  RWOBJECTTYPE_SECTIONMANIFEST = 0x10004,
  RWOBJECTTYPE_SECTIONTYPES = 0x10005,
  RWOBJECTTYPE_SECTIONEXTERNALARENAS = 0x10006,
  RWOBJECTTYPE_SECTIONSUBREFERENCES = 0x10007,
  RWOBJECTTYPE_SECTIONATOMS = 0x10008,
  RWOBJECTTYPE_DEFARENAIMPORTS = 0x10009,
  RWOBJECTTYPE_DEFARENAEXPORTS = 0x1000A,
  RWOBJECTTYPE_DEFARENATYPES = 0x1000B,
  RWOBJECTTYPE_DEFARENADEFINEDARENAID = 0x1000C,
  RWOBJECTTYPE_ATTRIBUTEPACKET = 0x1000D,
  RWOBJECTTYPE_ATTRIBUTEPACKET_DELEGATE = 0x1000E,
  RWOBJECTTYPE_BITTABLE = 0x1000F,
  RWOBJECTTYPE_ARENALOCALATOMTABLE = 0x10010,
  RWOBJECTTYPE_BASERESOURCE_START = 0x10030,
  RWOBJECTTYPE_BASERESOURCE_RESERVEDTO = 0x1003F,
  RWOBJECTTYPE_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 17102 */
const struct pegasus::tTOCEntry
{
  pegasus::tStringPtr m_Name;
  unsigned __int64 m_uiGuid;
  RwObjectType m_Type;
  void *m_pObject;
};

/* 17253 */
union pegasus::tRMeshData::<unnamed_tag>
{
  renderengine::DrawParameters *m_pDrawParameters;
  renderengine::DrawIndexedParameters *m_pDrawIndexedParameters;
};

/* 50 */
enum _D3DPRIMITIVETYPE : __int32
{
  D3DPT_POINTLIST = 0x1,
  D3DPT_LINELIST = 0x2,
  D3DPT_LINESTRIP = 0x3,
  D3DPT_TRIANGLELIST = 0x4,
  D3DPT_TRIANGLEFAN = 0x5,
  D3DPT_TRIANGLESTRIP = 0x6,
  D3DPT_RECTLIST = 0x8,
  D3DPT_QUADLIST = 0xD,
  D3DPT_FORCE_DWORD = 0x7FFFFFFF,
};

/* 17251 */
struct __cppobj renderengine::DrawParameters
{
  _D3DPRIMITIVETYPE primType;
  unsigned int startVertex;
  unsigned int vertexCount;
};

/* 17252 */
struct __cppobj renderengine::DrawIndexedParameters
{
  _D3DPRIMITIVETYPE primType;
  int baseVertexIndex;
  unsigned int startIndex;
  unsigned int indexCount;
};

/* 17254 */
struct __cppobj pegasus::tRMeshData
{
  pegasus::tAABB m_BBox;
  renderengine::VertexDescriptor *m_pVertexDescriptor;
  renderengine::MeshHelper *m_pMeshHelper;
  renderengine::IndexBuffer *m_pIndexBuffer;
  renderengine::VertexBuffer *m_pVertexBuffer;
  unsigned int m_uiNumVerts;
  pegasus::tRMeshData::<unnamed_tag> m_DrawParams;
  renderengine::IndexBuffer *m_pRemapTable;
  unsigned int m_bIsIndexed;
  unsigned int m_uiNumBoneMats;
  unsigned int m_uiNumBlendShapes;
  pegasus::tRMeshData::tBlendShapeInfo *m_pBlendShapeTable;
  pegasus::tStringPtr m_szBlendShapeNames;
};

/* 1011 */
enum renderengine::VertexFormat : __int32
{
  VERTEXFORMAT_FLOAT1 = 0x2C83A4,
  VERTEXFORMAT_FLOAT2 = 0x2C23A5,
  VERTEXFORMAT_FLOAT3 = 0x2A23B9,
  VERTEXFORMAT_FLOAT4 = 0x1A23A6,
  VERTEXFORMAT_INT1 = 0x2C83A1,
  VERTEXFORMAT_INT2 = 0x2C23A2,
  VERTEXFORMAT_INT4 = 0x1A23A3,
  VERTEXFORMAT_UINT1 = 0x2C82A1,
  VERTEXFORMAT_UINT2 = 0x2C22A2,
  VERTEXFORMAT_UINT4 = 0x1A22A3,
  VERTEXFORMAT_INT1N = 0x2C81A1,
  VERTEXFORMAT_INT2N = 0x2C21A2,
  VERTEXFORMAT_INT4N = 0x1A21A3,
  VERTEXFORMAT_UINT1N = 0x2C80A1,
  VERTEXFORMAT_UINT2N = 0x2C20A2,
  VERTEXFORMAT_UINT4N = 0x1A20A3,
  VERTEXFORMAT_D3DCOLOR = 0x182886,
  VERTEXFORMAT_UBYTE4 = 0x1A2286,
  VERTEXFORMAT_BYTE4 = 0x1A2386,
  VERTEXFORMAT_UBYTE4N = 0x1A2086,
  VERTEXFORMAT_BYTE4N = 0x1A2186,
  VERTEXFORMAT_SHORT2 = 0x2C2359,
  VERTEXFORMAT_SHORT4 = 0x1A235A,
  VERTEXFORMAT_USHORT2 = 0x2C2259,
  VERTEXFORMAT_USHORT4 = 0x1A225A,
  VERTEXFORMAT_SHORT2N = 0x2C2159,
  VERTEXFORMAT_SHORT4N = 0x1A215A,
  VERTEXFORMAT_USHORT2N = 0x2C2059,
  VERTEXFORMAT_USHORT4N = 0x1A205A,
  VERTEXFORMAT_UDEC3 = 0x2A2287,
  VERTEXFORMAT_DEC3 = 0x2A2387,
  VERTEXFORMAT_UDEC3N = 0x2A2087,
  VERTEXFORMAT_DEC3N = 0x2A2187,
  VERTEXFORMAT_UDEC4 = 0x1A2287,
  VERTEXFORMAT_DEC4 = 0x1A2387,
  VERTEXFORMAT_UDEC4N = 0x1A2087,
  VERTEXFORMAT_DEC4N = 0x1A2187,
  VERTEXFORMAT_UHEND3 = 0x2A2290,
  VERTEXFORMAT_HEND3 = 0x2A2390,
  VERTEXFORMAT_UHEND3N = 0x2A2090,
  VERTEXFORMAT_HEND3N = 0x2A2190,
  VERTEXFORMAT_UDHEN3 = 0x2A2291,
  VERTEXFORMAT_DHEN3 = 0x2A2391,
  VERTEXFORMAT_UDHEN3N = 0x2A2091,
  VERTEXFORMAT_DHEN3N = 0x2A2191,
  VERTEXFORMAT_FLOAT16_2 = 0x2C235F,
  VERTEXFORMAT_FLOAT16_4 = 0x1A2360,
  VERTEXFORMAT_COLOR = 0x14C86,
  VERTEXFORMAT_UNUSED = 0xFFFFFFFF,
  VERTEXFORMAT_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 16668 */
struct renderengine::VertexDescriptor::Element
{
  unsigned __int16 stream;
  unsigned __int16 offset;
  renderengine::VertexFormat format;
  unsigned __int8 method;
  unsigned __int8 usage;
  unsigned __int8 usageIndex;
  unsigned __int8 type;
  unsigned int elementClass;
};

/* 16705 */
const struct __cppobj renderengine::VertexDescriptor
{
  D3DVertexDeclaration *m_d3dVertexDeclaration;
  unsigned int m_typesFlags;
  unsigned __int16 m_numElements;
  __int16 m_refCount;
  unsigned __int16 m_instanceStreams;
  unsigned __int16 m_pad0;
  renderengine::VertexDescriptor::Element m_elements[1];
};

/* 17248 */
struct __cppobj renderengine::MeshHelper
{
  unsigned int m_numIndexBuffers;
  unsigned int m_numVertexBuffers;
  void *m_buffers[1];
};

/* 6805 */
struct D3DResource
{
  unsigned int Common;
  unsigned int ReferenceCount;
  unsigned int Fence;
  unsigned int ReadFence;
  unsigned int Identifier;
  unsigned int BaseFlush;
};

/* 7132 */
struct __cppobj D3DIndexBuffer : D3DResource
{
  unsigned int Address;
  unsigned int Size;
};

/* 17249 */
struct __cppobj renderengine::IndexBuffer : D3DIndexBuffer
{
  unsigned int m_numIndices;
};

/* 6943 */
struct $F1611EE1E966686941EB2BD5C0621C37
{
  unsigned __int32 Type : 2;
  unsigned __int32 BaseAddress : 30;
  unsigned __int32 Endian : 2;
  unsigned __int32 Size : 24;
  unsigned __int32 AddressClamp : 1;
  unsigned __int32 : 1;
  unsigned __int32 RequestSize : 2;
  unsigned __int32 ClampDisable : 2;
};

/* 6944 */
union GPUVERTEX_FETCH_CONSTANT
{
  $F1611EE1E966686941EB2BD5C0621C37 __s0;
  unsigned int dword[2];
};

/* 7131 */
struct __cppobj D3DVertexBuffer : D3DResource
{
  GPUVERTEX_FETCH_CONSTANT Format;
};

/* 17250 */
struct __cppobj renderengine::VertexBuffer : D3DVertexBuffer
{
  unsigned int m_bufferSize;
  unsigned int m_type;
};

/* 17256 */
struct pegasus::tRMeshData::tBlendShapeInfo
{
  pegasus::tRBlendShapeData *m_pBlendShapeItem;
  pegasus::tStringPtr m_szBlendShapeName;
  unsigned __int64 m_ui64HashName;
};

/* 6839 */
struct __cppobj D3DVertexDeclaration : D3DResource
{
};

/* 17255 */
struct __cppobj pegasus::tRBlendShapeData
{
  renderengine::VertexDescriptor *m_pVertexDescriptor;
  renderengine::MeshHelper *m_pMeshHelper;
  unsigned int m_uiNumMeshes;
  pegasus::tRMeshData **m_ppMeshTable;
  unsigned int m_uiNumBlendVertexWeights;
  float *m_pBlendVertexWeights;
};

/* 17257 */
union pegasus::tRMaterial::tRasterNamePtr
{
  unsigned int Offset;
  void *Pointer;
};

/* 17258 */
struct $457817F906C0CC728CA886B5FCEFDE8E
{
  unsigned __int64 m_uiGuid;
  pegasus::tRMaterial::tRasterNamePtr m_StreamName;
  void *m_pStream;
};

/* 17259 */
union $146BE816D3D23639C7A4613D85630DCE
{
  $457817F906C0CC728CA886B5FCEFDE8E __s0;
  float m_ShaderConstants[4];
};

/* 17260 */
struct pegasus::tRMaterial::tChannel
{
  pegasus::tStringPtr m_ShaderInput;
  unsigned __int16 m_uiFlags;
  unsigned __int16 m_uiImageChannel;
  unsigned int m_uiPad[2];
  $146BE816D3D23639C7A4613D85630DCE ___u4;
};

/* 17261 */
struct pegasus::tRMaterial
{
  unsigned int m_uiNumChannels;
  unsigned int m_uiFlags;
  pegasus::tRMaterial::tChannel *m_pChannels;
};

/* 17262 */
struct pegasus::tROptiMeshData::tBlendShapeInfo
{
  unsigned __int64 m_ui64HashName;
  pegasus::tRBlendShapeData *m_pBlendShapeItem;
  pegasus::tStringPtr m_szBlendShapeName;
};

/* 17263 */
struct __cppobj __declspec(align(8)) pegasus::tROptiMeshData
{
  pegasus::tAABB m_BBox;
  unsigned int m_uiNumVerts;
  pegasus::tRMaterial *m_pMaterial;
  renderengine::VertexDescriptor *m_pVertexDescriptor;
  renderengine::MeshHelper *m_pMeshHelper;
  renderengine::IndexBuffer *m_pIndexBuffer;
  renderengine::VertexBuffer *m_pVertexBuffer;
  unsigned int m_uiNumIslands;
  rw::math::vpu::Vector4 *m_pIslandAreas;
  pegasus::tAABB *m_pIslandAABBs;
  renderengine::DrawIndexedParameters *m_pIslandDrawParams;
  unsigned int m_uiNumRemapIndices;
  unsigned __int16 *m_pRemapTable;
  unsigned int m_uiNumBlendShapes;
  pegasus::tROptiMeshData::tBlendShapeInfo *m_pBlendShapeTable;
  pegasus::tStringPtr m_szBlendShapeNames;
};

/* 17264 */
union $C14B2615985F1F35F10773E12D4D48F9
{
  pegasus::tRMeshData *m_pMesh;
  pegasus::tROptiMeshData *m_pOptiMesh;
};

/* 17265 */
struct pegasus::tRModelData::tMeshData
{
  $C14B2615985F1F35F10773E12D4D48F9 ___u0;
  pegasus::tRMaterial *m_pMaterial;
};

/* 17266 */
struct __cppobj pegasus::tRModelData
{
  pegasus::tAABB m_BBox;
  rw::math::vpu::Matrix44 *m_pIBPMatrices;
  pegasus::tRModelData::tMeshData *m_pMeshTable;
  unsigned __int8 **m_pBoneNameTable;
  unsigned __int8 *m_pBoneNameList;
  unsigned __int16 m_iNumTotalBones;
  unsigned __int16 m_iNumMeshes;
  unsigned __int16 m_iNumBones;
  unsigned __int16 m_iNumIslands;
  pegasus::tAABB *m_pIslandAABBs;
  rw::math::vpu::Vector4 *m_pIslandAreas;
};

/* 15583 */
struct __cppobj rw::math::vpu::Matrix44
{
  rw::math::vpu::Vector4 xAxis;
  rw::math::vpu::Vector4 yAxis;
  rw::math::vpu::Vector4 zAxis;
  rw::math::vpu::Vector4 wAxis;
};

/* 17267 */
struct __cppobj __declspec(align(16)) pegasus::tHotPoint
{
  rw::math::vpu::Matrix44Affine m_Transform;
  pegasus::tAABB m_BBox;
  unsigned int m_eType;
};

/* 17275 */
union pegasus::tInstancePtr
{
  pegasus::tInstance *Pointer;
  unsigned int Offset;
};

/* 17277 */
union pegasus::tSplineSegmentPtr
{
  pegasus::tSplineSegment *Pointer;
  unsigned int Offset;
};

/* 17268 */
const struct pegasus::tSplineHeader
{
  unsigned __int64 m_uiGuid;
  unsigned __int64 m_uiGuidLocal;
  pegasus::tInstancePtr m_Instance;
  pegasus::tSplineSegmentPtr m_Head;
  pegasus::tSplineSegmentPtr m_Tail;
  unsigned int m_Pad;
};

/* 17274 */
struct __cppobj __declspec(align(8)) pegasus::tInstance
{
  rw::math::vpu::Matrix44Affine m_TransformMatrix;
  pegasus::tAABB m_BBox;
  unsigned __int64 m_uiGuid;
  unsigned __int64 m_uiGuidLocal;
  pegasus::tAttribPair m_AttribKey;
  pegasus::tRModelData *m_pRModel;
  pegasus::tCModelData *m_pCModel;
  pegasus::tEmbeddedData *m_pEmbedded;
  pegasus::tStringPtr m_Name;
  pegasus::tStringPtr m_Description;
  pegasus::tStringPtr m_Component;
  pegasus::tStringPtr m_Category;
};

/* 17276 */
union pegasus::tSplineHeaderPtr
{
  pegasus::tSplineHeader *Pointer;
  unsigned int Offset;
};

/* 17278 */
struct __cppobj __declspec(align(16)) pegasus::tSplineSegment
{
  rw::math::vpu::Matrix44 m_BasisMatrix;
  rw::math::vpu::Vector4 m_Inverse;
  pegasus::tAABB m_BBox;
  float m_fLength;
  float m_fDistance;
  pegasus::tSplineHeaderPtr m_Spline;
  pegasus::tSplineSegmentPtr m_Prev;
  pegasus::tSplineSegmentPtr m_Next;
};

/* 17273 */
struct __cppobj pegasus::tEmbeddedData
{
  unsigned int m_TypeID;
  int m_iNumHotPoints;
  int m_iNumGrindSplines;
  int m_iNumGrabSplines;
  int m_iNumVisualIndicators;
  pegasus::tEmbeddedDataPtr *m_pHotPoints;
  pegasus::tEmbeddedDataPtr *m_pGrindSplines;
  pegasus::tEmbeddedDataPtr *m_pGrabSplines;
  pegasus::tEmbeddedDataPtr *m_pVisualIndicators;
};

/* 17271 */
union $74DDCB0339C3A0605C0DD2FAF4327B27
{
  pegasus::tHotPoint *HotPointPtr;
  pegasus::tSplineHeader *GrindSplinePtr;
  pegasus::tGrab *GrabSplinePtr;
  pegasus::tVisualIndicator *VisualIndicatorPtr;
  unsigned int Offset;
};

/* 17272 */
struct pegasus::tEmbeddedDataPtr
{
  unsigned int m_iBoneIndex;
  $74DDCB0339C3A0605C0DD2FAF4327B27 ___u1;
};

/* 17269 */
struct __cppobj __declspec(align(16)) pegasus::tGrab
{
  pegasus::tAABB m_BBox;
  pegasus::tAttribPair m_AttribulatorKey;
  rw::math::vpu::Vector4 *m_pSplinePoints;
  rw::math::vpu::Vector4 *m_pApproachPoints;
  rw::math::vpu::Vector4 *m_pApproachVectors;
  unsigned int m_Flags;
  unsigned int m_Type;
  unsigned __int8 m_iNumSplinePoints;
  unsigned __int8 m_iNumApproachPoints;
  unsigned __int8 m_iNumApproachVectors;
  unsigned __int8 m_iPad;
};

/* 17270 */
struct __cppobj __declspec(align(8)) pegasus::tVisualIndicator
{
  unsigned __int64 m_uiGuid;
  unsigned __int64 m_uiGuidLocal;
  pegasus::tAABB m_BBox;
  unsigned int m_uiFlags;
  unsigned int m_uiNumSegs;
  rw::math::vpu::Matrix44 *m_pSegs;
};

/* 17408 */
struct __cppobj pegasus::tNavMesh2Data::Parameters
{
  unsigned int m_uiNumPoints;
  unsigned int m_uiNumEdges;
  unsigned int m_uiNumCells;
};

/* 17409 */
struct __cppobj pegasus::NavMesh2::tEdge
{
  unsigned int m_uiPointID[2];
  unsigned int m_uiCellID[2];
  rw::math::fpu::Vector3Template<float> m_Normal;
  rw::math::fpu::Vector3Template<float> m_Direction;
  float m_Magnitude;
};

/* 17410 */
struct pegasus::NavMesh2::tCellData
{
  float m_fFixedCost;
  float m_fTemporaryCost;
};

/* 17411 */
struct __cppobj pegasus::NavMesh2::tCell
{
  unsigned int m_uiPointID[3];
  unsigned int m_uiEdgeID[3];
  unsigned int m_uiNeighborID[3];
  rw::math::fpu::Vector3Template<float> m_Centroid;
  pegasus::NavMesh2::tCellData m_Data;
};

/* 17412 */
struct __cppobj pegasus::tWorldPainterQuadTreeData::tNode
{
  __int16 m_Children[4];
  unsigned __int16 m_DictionaryLookup;
};

/* 15024 */
struct __cppobj rw::math::vpu::Vector2
{
  __vector4 mV;
};

/* 17413 */
struct __cppobj __declspec(align(16)) pegasus::tWorldPainterQuadTreeData
{
  rw::math::vpu::Vector2 m_RootNodeTestSubtractor;
  rw::math::vpu::Vector2 m_RootNodeHalfWidth;
  unsigned int m_uiNumNodes;
  pegasus::tWorldPainterQuadTreeData::tNode *m_pRootNode;
};

/* 17414 */
struct pegasus::tWorldPainterDictionaryData::tEntryTable
{
  void *m_pEntry;
  unsigned int m_iSize;
};

/* 17415 */
struct __cppobj pegasus::tWorldPainterDictionaryData
{
  unsigned int m_NumTotalEntries;
  unsigned int m_NumEntryTableSlots;
  int m_eType;
  pegasus::tWorldPainterDictionaryData::tEntryTable *m_pEntryTable;
  void *m_pEntries;
};

/* 17416 */
struct __cppobj pegasus::tNavMesh2Data
{
  unsigned __int64 m_NeighbourIDs[5];
  int m_iQuadTreeDepth;
  __declspec(align(8)) pegasus::tAABB m_AABB;
  pegasus::tNavMesh2Data::Parameters m_Params;
  rw::math::fpu::Vector3Template<float> *m_pPointList;
  pegasus::NavMesh2::tEdge *m_pEdgeList;
  pegasus::NavMesh2::tCell *m_pCellList;
  pegasus::tWorldPainterQuadTreeData *m_pQuadTree;
  pegasus::tWorldPainterDictionaryData *m_pDictionary;
};

/* 17718 */
union pegasus::tWayPointPtr
{
  pegasus::tWayPoint *Pointer;
  unsigned int Offset;
};

/* 17715 */
const struct __cppobj pegasus::tWayPointGroup
{
  rw::math::vpu::Vector4 m_Centroid;
  pegasus::tAABB m_BBox;
  unsigned __int64 m_uiGuid;
  unsigned __int64 m_uiGuidLocal;
  pegasus::tAttribPair m_AttribKey;
  unsigned int m_NumWayPoints;
  pegasus::tWayPointPtr m_WayPoints;
  pegasus::tStringPtr m_Name;
  pegasus::tStringPtr m_Description;
};

/* 17716 */
union pegasus::tWayPointGroupPtr
{
  pegasus::tWayPointGroup *Pointer;
  unsigned int Offset;
};

/* 17717 */
struct __cppobj pegasus::tWayPoint
{
  rw::math::vpu::Vector4 m_Position;
  rw::math::vpu::Vector4 m_Orientation;
  unsigned int m_ID;
  pegasus::tWayPointGroupPtr m_Group;
  pegasus::tStringPtr m_Name;
  pegasus::tStringPtr m_Description;
};

/* 18277 */
struct __cppobj pegasus::tWorldPainterLayerData
{
  pegasus::tWorldPainterQuadTreeData *m_pQuadTree;
  pegasus::tWorldPainterDictionaryData *m_pDictionary;
  __int64 m_iLayerTypeGuid;
};

/* 23327 */
struct __cppobj __declspec(align(8)) pegasus::tRAINCurve
{
  rw::math::vpu::Matrix44 m_CurveMat;
  float m_fLength;
  unsigned int m_iNumParametricPoints;
  float *m_pParameterArcLengths;
};

/* 23328 */
struct __cppobj __declspec(align(16)) pegasus::tRAINPassage
{
  pegasus::tRAINCurve m_Curve;
  float m_fMaxPassageSpeed;
  unsigned int m_iOriginPinIndex;
  unsigned int m_iOriginLane;
  unsigned int m_iDestPinIndex;
  unsigned int m_iDestLane;
};

/* 23611 */
struct __cppobj __declspec(align(8)) pegasus::tRAINPin
{
  unsigned __int64 m_ItemID;
  pegasus::eRAINItemType m_ItemType;
  unsigned int m_ItemPinIndex;
  unsigned int m_uiNumLanes;
  unsigned int m_iNumAvailablePassages[4];
  int *m_AvailablePassages[4];
};

/* 23612 */
struct __cppobj __declspec(align(16)) pegasus::tRAINIntersection
{
  rw::math::vpu::Vector3 m_InnerVertices[4];
  rw::math::vpu::Vector3 m_OuterVertices[4];
  pegasus::tRAINPin m_IncomingRoads[4];
  pegasus::tRAINPin m_OutgoingRoads[4];
  float m_fSpeedLimit;
  unsigned int m_bLightControlled;
  unsigned __int64 m_NameID;
  pegasus::tRAINPassage *m_pPassages;
  unsigned int m_iNumPassages;
};

/* 23627 */
struct __cppobj __declspec(align(16)) pegasus::tRAINRoadSegment
{
  pegasus::tRAINCurve m_Curve;
  rw::math::vpu::Vector3 m_Vertices[4];
  rw::math::vpu::Vector3 m_Tangents[4];
  float m_fAggregateLength;
};

/* 23628 */
struct __cppobj pegasus::tRAINRoad
{
  unsigned __int64 m_NameID;
  pegasus::tRAINPin m_OriginPin;
  pegasus::tRAINPin m_DestinationPin;
  unsigned int m_iNumSegments;
  pegasus::tRAINRoadSegment *m_pSegments;
  float m_fSpeedLimit;
  unsigned int m_iNumLanes;
  float m_fWidth;
  float m_fLength;
  float m_fAggregateLength;
  unsigned int m_iStartSegment;
  unsigned __int64 m_SuperRoadID;
};

/* 23637 */
struct __cppobj __declspec(align(8)) pegasus::tRAINSuperRoad
{
  unsigned __int64 m_NameID;
  unsigned __int64 m_DestinationIntersectionID;
  unsigned int m_DestinationPinIndex;
  unsigned __int64 m_OriginIntersectionID;
  unsigned int m_OriginPinIndex;
  float m_fLength;
  float m_fWidth;
  float m_fParkingLaneWidth;
  float m_fSpeedLimit;
  unsigned int m_uiNumLanes;
  unsigned int m_uiFlags;
};

/* 23659 */
struct __cppobj __declspec(align(16)) pegasus::tRAINData
{
  pegasus::tAABB m_BBox;
  unsigned int m_iNumIntersections;
  unsigned int m_iNumRoads;
  unsigned int m_iNumSuperRoads;
  pegasus::tRAINIntersection *m_pIntersections;
  pegasus::tRAINRoad *m_pRoads;
  pegasus::tRAINSuperRoad *m_pSuperRoads;
};

/* 23770 */
const struct __cppobj pegasus::tWayPointData
{
  unsigned int m_uiNumWayPointGroups;
  unsigned int m_uiNumWayPoints;
  unsigned int m_uiNumStrings;
  pegasus::tWayPointGroupPtr m_WayPointGroups;
  pegasus::tWayPointPtr m_WayPoints;
  pegasus::tStringPtr m_StringList;
};

/* 24085 */
struct __cppobj pegasus::tInstanceData
{
  unsigned int m_TypeID;
  unsigned int m_uiNumInstances;
  unsigned int m_uiNumStrings;
  pegasus::tInstancePtr m_Instances;
  pegasus::tStringPtr m_StringList;
};

/* 24086 */
const struct __cppobj pegasus::tSpatialMap
{
  rw::collision::Volume *m_pMap;
  pegasus::tInstanceData *m_pTable;
};

/* 24101 */
struct __cppobj pegasus::tDMO
{
  rw::math::vpu::Matrix44Affine m_TransformMatrix;
  pegasus::tAABB m_BBox;
  unsigned __int64 m_uiGuid;
  unsigned __int64 m_uiGuidLocal;
  unsigned __int64 m_uiGuidInstance;
  pegasus::tInstancePtr m_Instance;
  pegasus::tStringPtr m_Name;
};

/* 24102 */
union pegasus::tDMOPtr
{
  pegasus::tDMO *Pointer;
  unsigned int Offset;
};

/* 24103 */
const struct __cppobj pegasus::tDMOData
{
  unsigned int m_TypeID;
  unsigned int m_uiNumDMOs;
  unsigned int m_uiNumStrings;
  pegasus::tDMOPtr m_DMOs;
  pegasus::tStringPtr m_StringList;
};

/* 24536 */
struct pegasus::tAudioMaterial
{
  pegasus::tAudioMaterial::eSurface m_eSurface;
  pegasus::tStringPtr m_Name;
};

/* 24537 */
struct pegasus::tPhysicsMaterial
{
  int m_iDummyForNow;
  pegasus::tStringPtr m_Name;
};

/* 24538 */
struct pegasus::tCMaterial
{
  pegasus::tAudioMaterial *m_pAudioMaterial;
  pegasus::tPhysicsMaterial *m_pPhysicsMaterial;
  pegasus::tStringPtr m_Name;
};

/* 24539 */
struct __cppobj pegasus::tCMaterialData::Parameters
{
  unsigned int m_uiNumAudioMaterials;
  unsigned int m_uiNumPhysicsMaterials;
  unsigned int m_uiNumCMaterials;
  unsigned int m_uiStringSize;
};

/* 24540 */
struct __cppobj pegasus::tCMaterialData
{
  unsigned int m_uiNumAudioMaterials;
  unsigned int m_uiNumPhysicsMaterials;
  unsigned int m_uiNumCMaterials;
  pegasus::tAudioMaterial *m_pAudioMaterials;
  pegasus::tPhysicsMaterial *m_pPhysicsMaterials;
  pegasus::tCMaterial *m_pCMaterials;
  unsigned __int8 *m_pStringList;
};

/* 24541 */
struct __cppobj pegasus::cSurfaceID
{
};

/* 24542 */
struct __cppobj pegasus::tCModelData::Parameters
{
  unsigned int m_iNumMeshes;
};

/* 24589 */
struct __cppobj pegasus::tCollisionBezier::Parameters
{
};

/* 15608 */
struct __cppobj rw::math::fpu::Vector4Template<float>
{
  float x;
  float y;
  float z;
  float w;
};

/* 24590 */
struct __cppobj __declspec(align(16)) pegasus::tCollisionBezier
{
  rw::math::fpu::Vector4Template<float> m_Points[16];
  rw::math::vpu::Matrix44 m_Ax;
  rw::math::vpu::Matrix44 m_Ay;
  rw::math::vpu::Matrix44 m_Az;
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_AABB;
  unsigned __int16 m_SurfaceID;
};

/* 24591 */
struct __cppobj pegasus::tInstanceData::Parameters
{
  unsigned int m_uiNumInstances;
  unsigned int m_uiNumStrings;
  unsigned int m_uiStringSize;
};

/* 24592 */
struct __cppobj pegasus::tDMOData::Parameters
{
  unsigned int m_uiNumDMOs;
  unsigned int m_uiNumStrings;
  unsigned int m_uiStringSize;
};

/* 24593 */
struct __cppobj pegasus::tHotPoint::TYPE
{
};

/* 24594 */
struct __cppobj pegasus::tEmbeddedData::Parameters
{
  int m_iNumHotPoints;
  int m_iNumGrindSplines;
  int m_iNumGrabSplines;
  int m_iNumVisualIndicators;
};

/* 24595 */
union pegasus::tGrabPtr
{
  pegasus::tGrab *Pointer;
  unsigned int Offset;
};

/* 24596 */
struct __cppobj pegasus::tGrabData::Parameters
{
  unsigned int m_uiNumGrabs;
  unsigned int m_uiNumSplinePoints;
  unsigned int m_uiNumApproachPoints;
  unsigned int m_uiNumApproachVectors;
};

/* 24597 */
struct __cppobj pegasus::tGrabData
{
  unsigned int m_uiNumGrabs;
  unsigned int m_uiNumSplinePoints;
  unsigned int m_uiNumApproachPoints;
  unsigned int m_uiNumApproachVectors;
  pegasus::tGrabPtr m_pGrabs;
  rw::math::vpu::Vector4 *m_pSPArray;
  rw::math::vpu::Vector4 *m_pAPArray;
  rw::math::vpu::Vector4 *m_pAVArray;
};

/* 24598 */
union pegasus::tTriggerInstancePtr
{
  pegasus::tTriggerInstance *Pointer;
  unsigned int Offset;
};

/* 24599 */
struct __cppobj pegasus::tTriggerInstanceData::Parameters
{
  unsigned int m_uiNumInstances;
  unsigned int m_uiNumStrings;
  unsigned int m_uiStringSize;
};

/* 24600 */
struct __cppobj pegasus::tTriggerInstanceData
{
  unsigned int m_TypeID;
  unsigned int m_uiNumInstances;
  unsigned int m_uiNumStrings;
  pegasus::tTriggerInstancePtr m_Instances;
  pegasus::tStringPtr m_StringList;
};

/* 24601 */
struct __cppobj pegasus::tSubLocationDesc
{
  rw::math::vpu::Matrix44Affine m_TransformMatrix;
  pegasus::tAABB m_BBox;
  pegasus::tStringPtr m_Name;
  pegasus::tStringPtr m_Description;
  unsigned __int8 m_PadBuffer[8];
};

/* 24602 */
union pegasus::tSubLocationDescPtr
{
  pegasus::tSubLocationDesc *Pointer;
  unsigned int Offset;
};

/* 24603 */
struct __cppobj pegasus::tLocationDesc
{
  rw::math::vpu::Matrix44Affine m_TransformMatrix;
  pegasus::tAABB m_BBox;
  unsigned int m_iNumSubLocations;
  pegasus::tSubLocationDescPtr m_SubLocations;
  pegasus::tStringPtr m_Name;
  pegasus::tStringPtr m_Description;
  unsigned __int64 m_uiGuid;
  unsigned __int8 m_PadBuffer[8];
};

/* 24604 */
union pegasus::tLocationDescPtr
{
  pegasus::tLocationDesc *Pointer;
  unsigned int Offset;
};

/* 24605 */
struct __cppobj pegasus::tLocationDescData::Parameters
{
  unsigned int m_uiNumLocationDescs;
  unsigned int m_uiNumSubLocationDescs;
  unsigned int m_uiNumStrings;
  unsigned int m_uiStringSize;
};

/* 24606 */
struct __cppobj pegasus::tLocationDescData
{
  unsigned int m_uiNumLocationDescs;
  unsigned int m_uiNumSubLocationDescs;
  unsigned int m_uiNumStrings;
  pegasus::tLocationDescPtr m_LocationDescs;
  pegasus::tSubLocationDescPtr m_SubLocationDescs;
  pegasus::tStringPtr m_StringList;
};

/* 24607 */
struct __cppobj pegasus::tMassiveData::Parameters
{
  unsigned int m_iNumEntities;
};

/* 24608 */
struct __cppobj pegasus::tMassiveData::tEntity
{
  rw::math::vpu::Vector4 m_Coords[4];
  rw::math::vpu::Vector4 m_Centroid;
  rw::math::vpu::Vector4 m_Normal;
  unsigned __int64 m_uiGuid;
  unsigned int m_uiRotationType;
  unsigned int m_Pad[1];
};

/* 24609 */
struct __cppobj pegasus::tMassiveData
{
  int m_iNumEntities;
  pegasus::tMassiveData::tEntity *m_pEntities;
};

/* 24610 */
struct __cppobj pegasus::tRBlendShapeData::Parameters
{
  unsigned int m_iNumOfMeshDatas;
  unsigned int m_iNumOfBlendVertexWeights;
};

/* 24611 */
struct __cppobj pegasus::tRMaterialData::Parameters
{
  unsigned int m_uiNumChannels;
  unsigned int m_uiNumMaterials;
  unsigned int m_uiStringSize;
};

/* 24612 */
struct __cppobj pegasus::tRMaterialData
{
  unsigned int m_uiNumMaterials;
  unsigned int m_uiNumChannels;
  pegasus::tRMaterial *m_pMaterials;
  pegasus::tRMaterial::tChannel *m_pChannels;
  pegasus::tStringPtr m_StringList;
};

/* 24613 */
struct __cppobj pegasus::tRMeshData::Parameters
{
  unsigned int m_iNumParams;
  unsigned int m_bIndexed;
  unsigned int m_iNumOfBlendShapes;
  unsigned int m_iBlendNamesLength;
};

/* 24614 */
struct __cppobj pegasus::tRModelData::Parameters
{
  unsigned int m_iNumMeshes;
  unsigned int m_iNumIslands;
  unsigned int m_iNumBones;
  unsigned int m_iBoneNameSize;
};

/* 24615 */
struct __cppobj pegasus::tROptiMeshData::Parameters
{
  unsigned int m_iNumIslands;
  unsigned int m_iNumRemapIndices;
  unsigned int m_iNumBlendShapes;
  unsigned int m_iBlendShapesNameLength;
};

/* 24616 */
struct __cppobj pegasus::tRollerDesc
{
  rw::math::vpu::Matrix44 m_TransformMatrix;
  pegasus::tAABB m_BBox;
  pegasus::tRModelData *m_pRModel;
  pegasus::tCModelData *m_pCModel;
  pegasus::tStringPtr m_Name;
  pegasus::tStringPtr m_Description;
};

/* 24617 */
union pegasus::tRollerDescPtr
{
  pegasus::tRollerDesc *Pointer;
  unsigned int Offset;
};

/* 24618 */
struct __cppobj pegasus::tRollerDescData::Parameters
{
  unsigned int m_uiNumRollerDescs;
  unsigned int m_uiNumStrings;
  unsigned int m_uiStringSize;
};

/* 24619 */
struct __cppobj pegasus::tRollerDescData
{
  unsigned int m_uiNumRollerDescs;
  unsigned int m_uiNumStrings;
  pegasus::tRollerDescPtr m_RollerDescs;
  pegasus::tStringPtr m_StringList;
};

/* 24620 */
struct __cppobj pegasus::tStatsData::Parameters
{
  unsigned int m_iNumStats;
};

/* 24621 */
struct __cppobj pegasus::tStatsData
{
  int m_iNumStats;
  int *m_pStats;
};

/* 24622 */
struct pegasus::tTableOfContents::tTypeMap
{
  RwObjectType m_Type;
  unsigned int m_uiIndex;
};

/* 24623 */
struct __cppobj pegasus::tTableOfContents
{
  unsigned int m_uiItemsCount;
  pegasus::tTOCEntry *m_pArray;
  pegasus::tStringPtr m_pNames;
  unsigned int m_uiTypeCount;
  pegasus::tTableOfContents::tTypeMap *m_pTypeMap;
};

/* 24624 */
struct __cppobj pegasus::tTableOfContents::cTypeIterator
{
  const pegasus::tTableOfContents *m_TOC;
  const RwObjectType m_Type;
  unsigned int m_uiPosition;
};

/* 24625 */
struct __cppobj pegasus::tWayPointData::Parameters
{
  unsigned int m_uiNumWayPointGroups;
  unsigned int m_uiNumWayPoints;
  unsigned int m_uiNumStrings;
  unsigned int m_uiStringSize;
};

/* 24626 */
union pegasus::tEmitterWayPointPtr
{
  pegasus::tEmitterWayPoint *Pointer;
  unsigned int Offset;
};

/* 24628 */
union pegasus::tEmitterWayPointGroupPtr
{
  pegasus::tEmitterWayPointGroup *Pointer;
  unsigned int Offset;
};

/* 24629 */
struct __cppobj pegasus::tEmitterWayPoint
{
  rw::math::vpu::Vector4 m_Position;
  rw::math::vpu::Vector4 m_Orientation;
  unsigned int m_ID;
  pegasus::tEmitterWayPointGroupPtr m_Group;
  pegasus::tStringPtr m_Name;
  unsigned int m_Pad[1];
};

/* 24627 */
struct __cppobj pegasus::tEmitterWayPointGroup
{
  rw::math::vpu::Vector4 m_Centroid;
  pegasus::tAABB m_BBox;
  unsigned __int64 m_uiGuid;
  unsigned __int64 m_uiGuidLocal;
  pegasus::tAttribPair m_AttribKey;
  unsigned int m_NumEmitterWayPoints;
  pegasus::tEmitterWayPointPtr m_EmitterWayPoints;
  pegasus::tStringPtr m_Name;
  unsigned int m_Pad[1];
};

/* 24630 */
struct __cppobj pegasus::tEmitterWayPointData::Parameters
{
  unsigned int m_uiNumEmitterWayPointGroups;
  unsigned int m_uiNumEmitterWayPoints;
  unsigned int m_uiNumStrings;
  unsigned int m_uiStringSize;
};

/* 24631 */
struct __cppobj pegasus::tEmitterWayPointData
{
  unsigned int m_uiNumEmitterWayPointGroups;
  unsigned int m_uiNumEmitterWayPoints;
  unsigned int m_uiNumStrings;
  pegasus::tEmitterWayPointGroupPtr m_EmitterWayPointGroups;
  pegasus::tEmitterWayPointPtr m_EmitterWayPoints;
  pegasus::tStringPtr m_StringList;
};

/* 24632 */
struct __cppobj pegasus::tWorldPainterDictionaryData::Parameters
{
  unsigned int m_uiNumTotalEntries;
  unsigned int m_uiNumEntryTableSlots;
  unsigned int m_uiTypeSize;
  int m_eType;
};

/* 24633 */
struct __cppobj pegasus::tWorldPainterLayerData::Parameters
{
  unsigned int m_uiDummy;
};

/* 24634 */
struct __cppobj pegasus::tWorldPainterQuadTreeData::Parameters
{
  unsigned int m_uiNumNodes;
};

/* 24635 */
struct __cppobj pegasus::tNavMeshData::Parameters
{
  unsigned int m_uiSizeInEdges;
};

/* 24636 */
struct __cppobj pegasus::NavMesh::tEdge
{
  unsigned __int16 m_uiPointID[2];
  unsigned __int16 m_uiCellID[2];
  rw::math::fpu::Vector3Template<float> m_Normal;
  rw::math::fpu::Vector3Template<float> m_Direction;
  float m_Magnitude;
};

/* 24637 */
struct pegasus::NavMesh::tCellData
{
  float m_fCost;
};

/* 24638 */
struct __cppobj pegasus::NavMesh::tCell
{
  unsigned __int16 m_uiPointID[3];
  unsigned __int16 m_uiEdgeID[3];
  unsigned __int16 m_uiNeighborID[3];
  rw::math::fpu::Vector3Template<float> m_Centroid;
  pegasus::NavMesh::tCellData m_Data;
};

/* 24639 */
struct __cppobj pegasus::tNavMeshData
{
  int m_iQuadTreeDepth;
  float m_fSizeInMeters;
  rw::math::fpu::Vector3Template<float> m_Location;
  pegasus::tNavMeshData::Parameters m_Params;
  rw::math::fpu::Vector3Template<float> *m_pPointList;
  pegasus::NavMesh::tEdge *m_pEdgeList;
  pegasus::NavMesh::tCell *m_pCellList;
  pegasus::tWorldPainterQuadTreeData *m_pQuadTree;
  pegasus::tWorldPainterDictionaryData *m_pDictionary;
};

/* 24640 */
struct __cppobj pegasus::tRAINData::Parameters
{
  unsigned int m_uiSize;
  unsigned int m_uiAlignment;
};

/* 24641 */
struct __cppobj pegasus::tAIPathNodeExtData
{
  float m_TrajectoryStartPos[3];
  float m_TrajectoryStartVel[3];
  float m_TrajectoryOffset[3];
  __int16 m_iTrickIndex;
  char m_AirSpin180Count;
  unsigned __int8 m_i8Flags;
};

/* 24642 */
struct __cppobj pegasus::tAIPathNode
{
  float m_Position[3];
  float m_Direction[3];
  unsigned __int8 m_BoardOrientation[4];
  unsigned __int8 m_SkaterOrientation[4];
  pegasus::tAIPathNodeExtData *m_pExtData;
  unsigned __int8 m_uiFramesSinceLastNode;
  unsigned __int8 m_uiNodeWidthLeft;
  unsigned __int8 m_uiNodeWidthRight;
  unsigned __int8 m_uiEventType;
  unsigned __int8 m_i8Flags;
  unsigned __int8 m_uiExtraData1;
  unsigned __int8 m_uiExtraData2;
  unsigned __int8 m_uiExtraData3;
};

/* 24643 */
struct __cppobj pegasus::tAIPathBranch
{
  unsigned __int8 m_PathID[16];
  int m_NodeIx;
  float m_fRatio;
};

/* 24644 */
struct __cppobj pegasus::tAIPathBranchGroup
{
  pegasus::tAIPathBranch *m_Branch;
  unsigned int m_iCount;
  int m_iSourceNode;
};

/* 24645 */
struct __cppobj pegasus::tAIPath
{
  pegasus::tAABB m_BBox;
  unsigned __int8 m_ID[16];
  pegasus::tAIPathNode *m_pNodes;
  int m_uiNumNodes;
  pegasus::tAIPathNodeExtData *m_pExtra;
  pegasus::tAIPathBranchGroup *m_pBranchGroup;
  int m_uiNumGroups;
  unsigned int m_BitFlags;
  unsigned __int64 m_AllowedSkaters;
  pegasus::tAIPath::ESkillLevel m_SkillLevel;
  int m_ExtraData1;
  int m_ExtraData2;
  int m_ExtraData3;
};

/* 24646 */
struct __cppobj pegasus::tAIPathData::Parameters
{
  unsigned int m_uiSize;
  unsigned int m_uiAlignment;
};

/* 24647 */
struct __cppobj pegasus::tAIPathData
{
  unsigned int m_uiNumOfPaths;
  pegasus::tAIPath *m_pPaths;
};

/* 24648 */
struct __cppobj pegasus::tLionData::Parameters
{
  unsigned int m_uiSize;
  unsigned int m_uiAlignment;
};

/* 24649 */
struct __cppobj pegasus::tLionData
{
  unsigned int m_iDummy;
};

/* 24650 */
struct __cppobj pegasus::tDepthMapCPUData::Parameters
{
  unsigned int m_NumOffsets;
  unsigned int m_NumRLEData;
};

/* 24651 */
struct __cppobj pegasus::tDepthMapCPUData
{
  float m_MinH;
  float m_MaxH;
  float m_MinX;
  float m_MaxX;
  float m_MinY;
  float m_MaxY;
  float m_Width;
  float m_Height;
  unsigned int m_NumOffsets;
  unsigned int *m_pOffsetData;
  unsigned int m_NumRLEData;
  unsigned __int8 *m_pRLEData;
};

/* 24652 */
struct __cppobj pegasus::tSpatialMap::Parameters
{
};

/* 24653 */
struct __cppobj pegasus::tIrradianceProbeData
{
  rw::math::vpu::Vector4 m_fSHRGB[9];
  rw::math::vpu::Vector3 m_fPos;
};

/* 24654 */
struct __cppobj pegasus::tIrradianceData
{
  unsigned int m_uiItems;
  pegasus::tIrradianceProbeData *m_aProbes;
};

/* 24655 */
struct __cppobj pegasus::tIrradianceData::Parameters
{
  unsigned int m_uiSize;
  unsigned int m_uiAlignment;
};

/* 24656 */
struct __cppobj pegasus::tAntiFrustum
{
  rw::math::vpu::Vector4 m_Points[4];
};

/* 24657 */
struct __cppobj pegasus::tAntiFrustumData::Parameters
{
  unsigned int m_uiNumAntiFrustums;
};

/* 24658 */
struct __cppobj pegasus::tAntiFrustumData
{
  pegasus::tAABB m_AABB;
  unsigned int m_uiNumAntiFrustums;
  pegasus::tAntiFrustum *m_pAntiFrustums;
  rw::collision::Volume *m_pSpatialMap;
  pegasus::tAABB *m_pAABBs;
};

/* 26635 */
struct __cppobj pegasus::tSplineData
{
  unsigned int m_uiNumSplines;
  unsigned int m_uiNumSegments;
  pegasus::tSplineHeaderPtr m_Splines;
  pegasus::tSplineSegmentPtr m_Segments;
};

/* 26959 */
struct __cppobj pegasus::tVisualIndicatorData
{
  unsigned int m_uiNumVIs;
  unsigned int m_uiNumSegs;
  pegasus::tVisualIndicator *m_pVIs;
  rw::math::vpu::Matrix44 *m_pSegs;
};

/* 34963 */
struct pegasus::tTypeToString
{
  unsigned int m_iType;
  const char *m_pszString;
};

/* 34965 */
union pegasus::tHotPointPtr
{
  pegasus::tHotPoint *Pointer;
  unsigned int Offset;
};

/* 34966 */
struct __cppobj pegasus::tHotPointData
{
  unsigned int m_uiNumHotPoints;
  pegasus::tHotPointPtr m_HotPoints;
};

/* 34967 */
struct __cppobj pegasus::tVersionData
{
  unsigned int m_uiVersion;
  unsigned int m_uiRevision;
};

