/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'sk82_na_zd.xex'
*/

struct AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy>;
struct rw::collision::Interval;
struct rw::collision::Feature;
struct rw::collision::GPInstance;
struct rw::collision::VolumeLineSegIntersectResult;
struct rw::collision::Volume::VTable;
struct rw::collision::Aggregate;
struct rw::collision::VolumeLineQuery;
struct rw::collision::VolumeBBoxQuery;
struct rw::collision::Aggregate::VTable;
struct rw::BitTable;

/* 2058 */
enum rw::collision::ObjectType : __int32
{
  RWCOBJECTTYPE_NA = 0x80000,
  RWCOBJECTTYPE_VOLUME = 0x80001,
  RWCOBJECTTYPE_SIMPLEMAPPEDARRAY = 0x80002,
  RWCOBJECTTYPE_TRIANGLEKDTREEPROCEDURAL = 0x80003,
  RWCOBJECTTYPE_KDTREEMAPPEDARRAY = 0x80004,
  RWCOBJECTTYPE_BBOX = 0x80005,
  RWCOBJECTTYPE_CLUSTEREDMESH = 0x80006,
  RWCOBJECTTYPE_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 2083 */
enum rw::collision::VolumeLineQuery::QueryResultsSet : __int32
{
  ALLLINEINTERSECTIONS = 0x0,
  ANYLINEINTERSECTION = 0x1,
  NEARESTLINEINTERSECTION = 0x2,
};

/* 2099 */
enum rw::collision::CMFlags : __int32
{
  CMFLAG_INT16VERTEX = 0x1,
  CMFLAG_INT16NORMAL = 0x2,
  CMFLAG_20BITCLUSTERINDEX = 0x4,
  CMFLAG_ONESIDED = 0x10,
  CMFLAG_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 2102 */
enum rw::collision::UnitTypeAndFlags : __int32
{
  UNITTYPE_OLDTRIANGLE = 0x0,
  UNITTYPE_TRIANGLE = 0x1,
  UNITTYPE_QUAD = 0x2,
  UNITTYPE_TRILIST = 0x3,
  UNITTYPE_MASK = 0xF,
  UNITFLAG_NORMAL = 0x10,
  UNITFLAG_EDGEANGLE = 0x20,
  UNITFLAG_GROUPID = 0x40,
  UNITFLAG_SURFACEID = 0x80,
  UNITFLAG_USEOLDTRI = 0xFF,
  UNITFLAG_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 2105 */
enum rw::collision::UnitEdgeFlags : __int32
{
  EDGEFLAG_ANGLEZERO = 0x1A,
  EDGEFLAG_ANGLEMASK = 0x1F,
  EDGEFLAG_EDGECONVEX = 0x20,
  EDGEFLAG_VERTEXDISABLE = 0x40,
  EDGEFLAG_EDGEUNMATCHED = 0x80,
};

/* 2114 */
enum rw::collision::ClusteredMeshCluster::<unnamed_tag> : __int32
{
  VERTICES_UNCOMPRESSED = 0x0,
  VERTICES_16BIT_COMPRESSED = 0x1,
  VERTICES_32BIT_COMPRESSED = 0x2,
};

/* 2131 */
enum rw::collision::VolumeType : __int32
{
  VOLUMETYPENULL = 0x0,
  VOLUMETYPESPHERE = 0x1,
  VOLUMETYPECAPSULE = 0x2,
  VOLUMETYPETRIANGLE = 0x3,
  VOLUMETYPEBOX = 0x4,
  VOLUMETYPECYLINDER = 0x5,
  VOLUMETYPEAGGREGATE = 0x6,
  VOLUMETYPENUMINTERNALTYPES = 0x7,
  VOLUMETYPEFORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 2137 */
enum rw::collision::VolumeFlag : __int32
{
  VOLUMEFLAG_ISENABLED = 0x1,
  VOLUMEFLAG_TRIANGLENORMALISDIRTY = 0x2,
  VOLUMEFLAG_TRIANGLEONESIDED = 0x10,
  VOLUMEFLAG_TRIANGLEEDGE0CONVEX = 0x20,
  VOLUMEFLAG_TRIANGLEEDGE1CONVEX = 0x40,
  VOLUMEFLAG_TRIANGLEEDGE2CONVEX = 0x80,
  VOLUMEFLAG_TRIANGLEUSEEDGECOS = 0x100,
  VOLUMEFLAG_TRIANGLEVERT0DISABLE = 0x200,
  VOLUMEFLAG_TRIANGLEVERT1DISABLE = 0x400,
  VOLUMEFLAG_TRIANGLEVERT2DISABLE = 0x800,
  VOLUMEFLAG_TRIANGLEDEFAULT = 0x1E1,
  VOLUMEFLAG_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 2170 */
enum rw::collision::Feature::<unnamed_tag> : __int32
{
  MAXEDGECOUNT = 0x8,
};

/* 2184 */
enum rw::collision::GPInstance::VolumeType : __int32
{
  UNUSED = 0x0,
  SPHERE = 0x1,
  CAPSULE = 0x2,
  TRIANGLE = 0x3,
  BOX = 0x4,
  CYLINDER = 0x5,
  NUMINTERNALTYPES = 0x6,
  FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 2186 */
enum rw::collision::GPInstance::VolumeFlag : __int32
{
  FLAG_TRIANGLEONESIDED = 0x10,
  FLAG_TRIANGLEEDGE0CONVEX = 0x20,
  FLAG_TRIANGLEEDGE1CONVEX = 0x40,
  FLAG_TRIANGLEEDGE2CONVEX = 0x80,
  FLAG_TRIANGLEUSEEDGECOS = 0x100,
  FLAG_TRIANGLEVERT0DISABLE = 0x200,
  FLAG_TRIANGLEVERT1DISABLE = 0x400,
  FLAG_TRIANGLEVERT2DISABLE = 0x800,
  FLAG_TRIANGLEDEFAULT = 0x1E0,
  FLAG_TRIANGLEOLDMASK = 0xF0,
  FLAG_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 2227 */
enum rw::collision::PrimitivePairIntersectResult::<unnamed_tag> : __int32
{
  MAXPOINTCOUNT = 0x10,
};

/* 2270 */
enum rw::collision::Frustum::PlaneIndex : __int32
{
  PLANE_NA = 0x0,
  PLANE_FRONT = 0x0,
  PLANE_BACK = 0x1,
  PLANE_LEFT = 0x2,
  PLANE_RIGHT = 0x3,
  PLANE_TOP = 0x4,
  PLANE_BOTTOM = 0x5,
  PLANE_MAX = 0x6,
  PLANE_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 4536 */
enum rw::collision::FixupReason : __int32
{
  UNASSIGNED = 0x0,
  FACE = 0x1,
  CONVEXEDGE = 0x2,
  CONCAVEEDGE = 0x3,
  DISABLEDVERTEX = 0x4,
  ENABLEDVERTEX = 0x5,
};

/* 6192 */
enum rw::collision::rwc_Region : __int32
{
  rwc_REGION_VERT0 = 0x0,
  rwc_REGION_VERT1 = 0x1,
  rwc_REGION_VERT2 = 0x2,
  rwc_REGION_EDGE0 = 0x3,
  rwc_REGION_EDGE1 = 0x4,
  rwc_REGION_EDGE2 = 0x5,
  rwc_REGION_FACE = 0x6,
  rwc_REGION_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 6193 */
enum rw::collision::TriangleFeatureType : __int32
{
  TFT_FACE = 0x0,
  TFT_EDGE0 = 0x1,
  TFT_EDGE1 = 0x2,
  TFT_VERT1 = 0x3,
  TFT_EDGE2 = 0x4,
  TFT_VERT0 = 0x5,
  TFT_VERT2 = 0x6,
  TFT_FORCEENUMSIZEINT = 0x7FFFFFFF,
};

/* 6866 */
struct $91D1B2149FAC90180ECB9AC277F76009
{
  float x;
  float y;
  float z;
  float w;
};

/* 6867 */
union $B7B8F02308E65255310DBC0B27D2928D
{
  $91D1B2149FAC90180ECB9AC277F76009 __s0;
  float v[4];
  unsigned int u[4];
};

/* 6868 */
struct __vector4
{
  $B7B8F02308E65255310DBC0B27D2928D ___u0;
};

/* 15011 */
struct __cppobj rw::math::vpu::Vector3
{
  __vector4 mV;
};

/* 15012 */
struct __cppobj rw::math::vpu::Matrix44Affine
{
  rw::math::vpu::Vector3 xAxis;
  rw::math::vpu::Vector3 yAxis;
  rw::math::vpu::Vector3 zAxis;
  rw::math::vpu::Vector3 wAxis;
};

/* 16819 */
struct rw::collision::AggregateSpecificData
{
  rw::collision::Aggregate *agg;
};

/* 16820 */
struct rw::collision::SphereSpecificData
{
  void *nothing;
};

/* 16821 */
struct rw::collision::CapsuleSpecificData
{
  float hh;
};

/* 16822 */
struct rw::collision::TriangleSpecificData
{
  float edgeCos0;
  float edgeCos1;
  float edgeCos2;
};

/* 16823 */
struct rw::collision::BoxSpecificData
{
  float hx;
  float hy;
  float hz;
};

/* 16824 */
struct rw::collision::CylinderSpecificData
{
  float hh;
  float innerRadius;
};

/* 16825 */
union $877A47AA15D4BD367D845A958F733A2C
{
  rw::collision::AggregateSpecificData aggregateData;
  rw::collision::SphereSpecificData sphereData;
  rw::collision::CapsuleSpecificData capsuleData;
  rw::collision::TriangleSpecificData triangleData;
  rw::collision::BoxSpecificData boxData;
  rw::collision::CylinderSpecificData cylinderData;
  unsigned int sizeOfTargetPointer[2];
};

/* 16806 */
struct __cppobj rw::collision::Volume
{
  rw::math::vpu::Matrix44Affine transform;
  rw::collision::Volume::VTable *vTable;
  $877A47AA15D4BD367D845A958F733A2C ___u2;
  float radius;
  unsigned int groupID;
  unsigned int surfaceID;
  unsigned int m_flags;
};

/* 16814 */
struct rw::collision::Volume::VTable
{
  rw::collision::VolumeType typeID;
  unsigned int (__cdecl *getBBox)(rw::collision::Volume *this, const rw::math::vpu::Matrix44Affine *, unsigned int, AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> *);
  rw::math::vpu::Vector3 *(__cdecl *getBBoxDiag)(rw::collision::Volume *this, rw::math::vpu::Vector3 *result);
  unsigned int (__cdecl *getInterval)(rw::collision::Volume *this, const rw::math::vpu::Vector3 *, rw::collision::Interval *);
  unsigned int (__cdecl *getMaximumFeature)(rw::collision::Volume *this, unsigned int, const rw::math::vpu::Vector3 *, rw::collision::Feature *);
  unsigned int (__cdecl *createGPInstance)(rw::collision::Volume *this, rw::collision::GPInstance *, const rw::math::vpu::Matrix44Affine *);
  unsigned int (__cdecl *lineSegIntersect)(rw::collision::Volume *this, const rw::math::vpu::Vector3 *, const rw::math::vpu::Vector3 *, const rw::math::vpu::Matrix44Affine *, rw::collision::VolumeLineSegIntersectResult *, const float);
  void (__cdecl *release)(rw::collision::Volume *this);
  const char *name;
  unsigned int flags;
};

/* 16803 */
const struct __cppobj AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy>
{
  rw::math::vpu::Vector3 m_min;
  rw::math::vpu::Vector3 m_max;
};

/* 16815 */
struct __cppobj rw::collision::Aggregate
{
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_AABB;
  rw::collision::Aggregate::VTable *m_vTable;
  unsigned int m_numTagBits;
  unsigned int m_numVolumes;
  unsigned int pad;
};

/* 15125 */
struct __cppobj rw::math::vpu::VecFloat
{
  __vector4 mV;
};

/* 16807 */
struct __cppobj __declspec(align(16)) rw::collision::Interval
{
  rw::math::vpu::VecFloat min;
  rw::math::vpu::VecFloat max;
  float padding[2];
};

/* 16808 */
struct __cppobj rw::collision::FeatureEdge
{
  rw::math::vpu::Vector3 base;
  rw::math::vpu::Vector3 dir;
  rw::math::vpu::Vector3 pn;
  rw::math::vpu::VecFloat length;
};

/* 16809 */
struct __cppobj rw::collision::Feature
{
  unsigned int region;
  __declspec(align(16)) rw::collision::FeatureEdge edges[8];
  rw::math::vpu::Vector3 ownNormal;
  rw::math::vpu::Vector3 pt;
  int numedges;
};

/* 16811 */
struct rw::collision::GPInstance::VolumeMethods
{
  void (__cdecl *mGetMaximumFeature)(rw::collision::GPInstance *this, unsigned int, const rw::math::vpu::Vector3 *, rw::collision::Feature *);
  void (__cdecl *mGetInterval)(rw::collision::GPInstance *this, const rw::math::vpu::Vector3 *, rw::collision::Interval *);
  void (__cdecl *mGetIntervals)(rw::collision::GPInstance *this, const rw::math::vpu::Vector3 *, unsigned int, rw::collision::Interval *);
  void (__cdecl *mGetBBox)(rw::collision::GPInstance *this, AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> *);
};

/* 16810 */
struct __cppobj __declspec(align(16)) rw::collision::GPInstance
{
  rw::math::vpu::Vector3 mPos;
  rw::math::vpu::Vector3 mFaceNormals[3];
  rw::math::vpu::Vector3 mEdgeDirections[3];
  rw::math::vpu::Vector3 mDimensions;
  float mFatness;
  unsigned int mVolumeTag;
  unsigned int mUserTag;
  unsigned __int8 mNumFaceNormals;
  unsigned __int8 mNumEdgeDirections;
  rw::collision::GPInstance::VolumeType mVolumeType;
  unsigned int mFlags;
  float mEdgeData[3];
  rw::collision::GPInstance::VolumeMethods mVolumeMethods;
};

/* 16812 */
struct __cppobj rw::collision::VolRef
{
  const rw::collision::Volume *volume;
  rw::math::vpu::Matrix44Affine *tm;
  __declspec(align(16)) rw::math::vpu::Matrix44Affine tmContents;
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> bBox;
  unsigned int tag;
  unsigned __int8 numTagBits;
};

/* 16813 */
struct __cppobj rw::collision::VolumeLineSegIntersectResult
{
  const rw::collision::Volume *v;
  __declspec(align(16)) rw::math::vpu::Vector3 position;
  rw::math::vpu::Vector3 normal;
  rw::math::vpu::Vector3 volParam;
  float lineParam;
  rw::collision::VolRef vRef;
};

/* 16818 */
struct rw::collision::Aggregate::VTable
{
  rw::collision::ObjectType m_type;
  unsigned int (__cdecl *m_GetSize)(rw::collision::Aggregate *this);
  unsigned int m_alignment;
  unsigned int m_isProcedural;
  void (__cdecl *m_Update)(rw::collision::Aggregate *this);
  unsigned int (__cdecl *m_LineIntersectionQuery)(rw::collision::Aggregate *this, rw::collision::VolumeLineQuery *, const rw::math::vpu::Matrix44Affine *);
  unsigned int (__cdecl *m_BBoxOverlapQuery)(rw::collision::Aggregate *this, rw::collision::VolumeBBoxQuery *, const rw::math::vpu::Matrix44Affine *);
};

/* 16816 */
struct __cppobj __declspec(align(8)) rw::collision::VolumeLineQuery
{
  const rw::collision::Volume **m_inputVols;
  const rw::math::vpu::Matrix44Affine **m_inputMats;
  unsigned int m_numInputs;
  unsigned int m_currInput;
  rw::collision::VolumeLineSegIntersectResult *m_resBuffer;
  unsigned int m_resCount;
  unsigned int m_resMax;
  unsigned int m_resBufferSize;
  rw::math::vpu::Vector3 m_pt1;
  rw::math::vpu::Vector3 m_pt2;
  float m_fatness;
  rw::collision::VolRef *m_stackVRefBuffer;
  rw::collision::VolRef m_currVRef;
  unsigned int m_stackNext;
  unsigned int m_stackMax;
  rw::collision::VolRef *m_primVRefBuffer;
  unsigned int m_primNext;
  unsigned int m_primBufferSize;
  rw::collision::Volume *m_instVolPool;
  unsigned int m_instVolCount;
  unsigned int m_instVolMax;
  unsigned int m_aggIndex;
  void *m_spatialMapQueryMem;
  void *m_curSpatialMapQuery;
  float m_endClipVal;
  rw::collision::VolumeLineQuery::QueryResultsSet m_resultsSet;
  unsigned int m_tag;
  unsigned __int8 m_numTagBits;
};

/* 16817 */
struct __cppobj __declspec(align(16)) rw::collision::VolumeBBoxQuery
{
  const rw::collision::Volume **m_inputVols;
  const rw::math::vpu::Matrix44Affine **m_inputMats;
  unsigned int m_numInputs;
  unsigned int m_currInput;
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_aabb;
  rw::collision::VolRef *m_stackVRefBuffer;
  rw::collision::VolRef m_currVRef;
  unsigned int m_stackNext;
  unsigned int m_stackMax;
  rw::collision::VolRef *m_primVRefBuffer;
  unsigned int m_primNext;
  unsigned int m_primBufferSize;
  rw::collision::Volume *m_instVolPool;
  unsigned int m_instVolCount;
  unsigned int m_instVolMax;
  unsigned int m_aggIndex;
  void *m_spatialMapQueryMem;
  void *m_curSpatialMapQuery;
  unsigned int m_tag;
  unsigned __int8 m_numTagBits;
};

/* 16891 */
struct rw::collision::Octree::Node
{
  unsigned __int16 m_parent;
  unsigned __int16 m_childOfParent;
  unsigned __int16 m_stuckEntries;
  unsigned __int16 m_childTypes;
  unsigned __int16 m_childRefs[8];
  unsigned __int8 m_pushCounts[8];
};

/* 16892 */
struct rw::collision::Octree::Entry
{
  unsigned __int16 m_group;
  unsigned __int16 m_next;
  unsigned __int16 m_node;
  unsigned __int8 m_child;
  unsigned __int8 m_corner;
};

/* 16893 */
struct __cppobj __declspec(align(16)) rw::collision::Octree
{
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_extent;
  unsigned int m_maxEntries;
  unsigned int m_maxNodes;
  unsigned int m_nodeFreeList;
  rw::collision::Octree::Node *m_nodes;
  rw::collision::Octree::Entry *m_entries;
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> *m_bboxes;
};

/* 17121 */
const struct __cppobj rw::collision::PrimitivePairIntersectResult
{
  const rw::collision::Volume *v1;
  unsigned int tag1;
  const rw::collision::Volume *v2;
  unsigned int tag2;
  int vNindex;
  rw::collision::Feature f1;
  rw::collision::Feature f2;
  rw::math::vpu::Vector3 sepDir;
  float sepDist;
  __declspec(align(16)) rw::math::vpu::Vector3 normal;
  rw::math::vpu::Vector3 pointOn1;
  rw::math::vpu::Vector3 pointOn2;
  float distance;
  __declspec(align(16)) rw::math::vpu::Vector3 pointsOn1[16];
  rw::math::vpu::Vector3 pointsOn2[16];
  float distances[16];
  unsigned int numPoints;
};

/* 17292 */
struct __cppobj rw::collision::MappedArray : rw::collision::Aggregate
{
  rw::collision::Volume *m_volumes;
  unsigned int padma[3];
};

/* 17293 */
struct __cppobj rw::collision::SimpleMappedArray : rw::collision::MappedArray
{
};

/* 17441 */
struct __cppobj rw::collision::BoxVolume : rw::collision::Volume
{
};

/* 17730 */
const struct __cppobj rw::collision::CapsuleVolume : rw::collision::Volume
{
};

/* 23000 */
struct __cppobj rw::collision::Procedural : rw::collision::Aggregate
{
};

/* 23001 */
struct rw::collision::KDTree::NodeRef
{
  unsigned int m_content;
  unsigned int m_index;
};

/* 23002 */
struct rw::collision::KDTree::BranchNode
{
  unsigned int m_parent;
  unsigned int m_axis;
  rw::collision::KDTree::NodeRef m_childRefs[2];
  float m_extents[2];
};

/* 23003 */
struct __cppobj rw::collision::KDTree
{
  rw::collision::KDTree::BranchNode *m_branchNodes;
  unsigned int m_numBranchNodes;
  unsigned int m_numEntries;
  __declspec(align(8)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bbox;
};

/* 23004 */
struct rw::collision::ClusterParams
{
  float mVertexCompressionGranularity;
  unsigned __int16 mFlags;
  unsigned __int8 mGroupIdSize;
  unsigned __int8 mSurfaceIdSize;
};

/* 23005 */
const struct __cppobj __declspec(align(8)) rw::collision::ClusteredMesh : rw::collision::Procedural
{
  rw::collision::KDTree *mKDTree;
  unsigned int *mCluster;
  rw::collision::ClusterParams mClusterParams;
  unsigned int mNumClusters;
  unsigned int mMaxClusters;
  unsigned int mNumUnits;
  unsigned int mMaxUnits;
  unsigned int mSizeOfThis;
  unsigned __int16 mDefaultGroupId;
  unsigned __int16 mDefaultSurfaceId;
  unsigned __int8 mDefaultEdgeAngle;
};

/* 23047 */
struct __cppobj rw::collision::GPTriangle : rw::collision::GPInstance
{
};

/* 23107 */
struct __cppobj rw::collision::GPInstance::ContactPoints::PointPair
{
  rw::math::vpu::Vector3 p1;
  rw::math::vpu::Vector3 p2;
};

/* 23108 */
struct __cppobj rw::collision::GPInstance::ContactPoints
{
  unsigned int volumeTag1;
  unsigned int volumeTag2;
  unsigned int userTag1;
  unsigned int userTag2;
  unsigned int numPoints;
  __declspec(align(16)) rw::math::vpu::Vector3 normal;
  rw::collision::GPInstance::ContactPoints::PointPair pointPairs[16];
};

/* 24543 */
struct __cppobj rw::collision::AALineClipper
{
  rw::math::vpu::Vector3 m_origin;
  rw::math::vpu::Vector3 m_delta;
  rw::math::vpu::Vector3 m_recip;
  rw::math::vpu::Vector3 m_padding;
};

/* 24544 */
struct rw::collision::KDTreeLineQueryBase::StackElement
{
  rw::collision::KDTree::NodeRef m_nodeRef;
  float m_pa;
  float m_pb;
};

/* 24545 */
struct __cppobj rw::collision::KDTreeLineQueryBase
{
  const rw::collision::KDTree *m_kdtree;
  __declspec(align(16)) rw::collision::AALineClipper m_lineClipper;
  rw::collision::KDTreeLineQueryBase::StackElement m_stack[32];
  unsigned int m_top;
  unsigned int m_leafCount;
  unsigned int m_nextEntry;
};

/* 24546 */
struct __cppobj rw::collision::KDTreeLineQuery : rw::collision::KDTreeLineQueryBase
{
};

/* 24547 */
struct __cppobj rw::collision::KDTreeBBoxQueryBase
{
  const rw::collision::KDTree *m_kdtree;
  __declspec(align(16)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bbox;
  unsigned int m_stack[32];
  unsigned int m_top;
  unsigned int m_resultCount;
  unsigned int m_nextEntry;
};

/* 24548 */
struct __cppobj rw::collision::KDTreeBBoxQuery : rw::collision::KDTreeBBoxQueryBase
{
};

/* 24549 */
struct __cppobj rw::collision::GPSphere : rw::collision::GPInstance
{
};

/* 24550 */
struct __cppobj rw::collision::GPCapsule : rw::collision::GPInstance
{
};

/* 24551 */
struct __cppobj rw::collision::GPBox : rw::collision::GPInstance
{
};

/* 24552 */
struct __cppobj rw::collision::GPCylinder : rw::collision::GPInstance
{
};

/* 24553 */
struct rw::collision::Fraction
{
  float num;
  float den;
};

/* 24554 */
struct __cppobj rw::collision::Volume::VTablePtrToID
{
};

/* 24555 */
struct __cppobj rw::collision::Volume::VTableIDToPtr
{
};

/* 15597 */
struct __cppobj rw::math::vpu::Vector3Plus
{
  __vector4 mV;
};

/* 24556 */
struct __cppobj rw::collision::Plane
{
  rw::math::vpu::Vector3Plus m_data;
};

/* 24557 */
struct __cppobj __declspec(align(8)) rw::collision::Octree::LineQuery::StackElement
{
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bb;
  float m_p[2];
  unsigned __int16 m_node;
};

/* 24558 */
struct __declspec(align(4)) rw::collision::Octree::LineQuery::Result
{
  float m_p[2];
  unsigned __int16 m_node;
};

/* 24559 */
struct __cppobj rw::collision::Octree::LineQuery
{
  const rw::collision::Octree *m_octree;
  __declspec(align(16)) rw::collision::AALineClipper m_clipper;
  rw::math::vpu::Vector3 m_recipPad;
  unsigned int m_swap;
  __declspec(align(16)) rw::collision::Octree::LineQuery::StackElement m_stack[211];
  unsigned int m_top;
  rw::collision::Octree::LineQuery::Result m_results[9];
  int m_curResult;
  unsigned int m_nextEntry;
};

/* 24560 */
struct __cppobj __declspec(align(16)) rw::collision::Octree::BBoxQuery::StackElement
{
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bb;
  unsigned __int16 m_node;
};

/* 24561 */
struct __cppobj rw::collision::Octree::BBoxQuery
{
  const rw::collision::Octree *m_octree;
  __declspec(align(16)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bbox;
  rw::collision::Octree::BBoxQuery::StackElement m_stack[211];
  unsigned int m_top;
  unsigned __int16 m_results[9];
  int m_curResult;
  unsigned int m_nextEntry;
};

/* 24562 */
struct __cppobj rw::collision::Frustum
{
  rw::collision::Plane m_planes[6];
};

/* 24563 */
struct __cppobj rw::collision::SphereVolume : rw::collision::Volume
{
};

/* 24564 */
struct __cppobj rw::collision::SphereVolume::ObjectDescriptor
{
};

/* 24565 */
struct __cppobj rw::collision::CapsuleVolume::ObjectDescriptor
{
};

/* 24566 */
struct __cppobj rw::collision::CylinderVolume : rw::collision::Volume
{
};

/* 24567 */
struct __cppobj rw::collision::CylinderVolume::ObjectDescriptor
{
};

/* 24568 */
struct __cppobj rw::collision::KDTreeMappedArray : rw::collision::MappedArray
{
  rw::collision::KDTree *m_map;
  unsigned int padkdtma[3];
};

/* 24569 */
struct __cppobj rw::collision::KDTreeMappedArray::ObjectDescriptor
{
  unsigned int m_numVols;
  unsigned int m_numNodes;
  __declspec(align(16)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bbox;
};

/* 24570 */
struct __cppobj rw::collision::SimpleMappedArray::ObjectDescriptor
{
  unsigned int m_numVols;
};

/* 24571 */
struct rw::collision::VolRefPair
{
  rw::collision::VolRef *vRef1;
  rw::collision::VolRef *vRef2;
};

/* 24572 */
struct rw::collision::VolRef1xN
{
  rw::collision::VolRef *vRef1;
  unsigned int vRefsNCount;
  unsigned int volumesSwapped;
  rw::collision::VolRef *vRefsN[1];
};

/* 24573 */
struct __cppobj rw::collision::VolumeVolumeQuery
{
  const rw::collision::Volume **m_inputVols;
  const rw::math::vpu::Matrix44Affine **m_inputMats;
  unsigned int m_numInputs;
  unsigned int m_currInput;
  const rw::BitTable *m_cullTable;
  float m_padding;
  rw::collision::VolRefPair *m_volRefPairBuffer;
  unsigned int m_volRefPairCount;
  unsigned int m_volRefPairBufferSize;
  rw::collision::VolRef1xN *m_volRef1xNBuffer;
  unsigned int m_volRef1xNCount;
  rw::collision::GPInstance *m_instancingSPR;
  rw::collision::PrimitivePairIntersectResult *m_intersectionBuffer;
  int m_intersectionBufferMaxSize;
  const rw::collision::Volume *m_queryVol;
  const rw::math::vpu::Matrix44Affine *m_queryMtx;
  rw::collision::VolumeBBoxQuery *m_bBoxQueryAtoB;
  rw::collision::VolumeBBoxQuery *m_bBoxQueryBtoA;
};

/* 16830 */
const struct __cppobj rw::BitTable
{
  unsigned int m_rows;
  unsigned int m_columns;
  unsigned int m_arraySize;
  unsigned int m_array[1];
};

/* 24574 */
struct __cppobj rw::collision::TriangleVolume : rw::collision::Volume
{
};

/* 24575 */
struct __cppobj rw::collision::TriangleVolume::ObjectDescriptor
{
};

/* 24576 */
struct __cppobj rw::collision::BoxVolume::ObjectDescriptor
{
};

/* 24577 */
struct __cppobj rw::collision::AggregateVolume : rw::collision::Volume
{
};

/* 24578 */
struct __cppobj rw::collision::AggregateVolume::ObjectDescriptor
{
};

/* 24579 */
struct rw::collision::TriangleKDTreeProcedural::Triangle
{
  unsigned int indices[3];
  unsigned int id;
};

/* 24580 */
struct __cppobj __declspec(align(16)) rw::collision::TriangleKDTreeProcedural : rw::collision::Procedural
{
  unsigned int m_numVerts;
  rw::collision::TriangleKDTreeProcedural::Triangle *m_tris;
  rw::math::vpu::Vector3 *m_verts;
  rw::collision::KDTree *m_map;
  unsigned int *m_flags;
};

/* 24581 */
struct __cppobj rw::collision::TriangleKDTreeProcedural::ObjectDescriptor
{
  unsigned int m_numVerts;
  unsigned int m_numTris;
  unsigned int m_numNodes;
  __declspec(align(8)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bbox;
};

/* 24582 */
struct __cppobj rw::collision::ClusteredMeshCluster
{
  unsigned __int16 unitCount;
  unsigned __int16 unitDataSize;
  unsigned __int16 unitDataStart;
  unsigned __int16 normalStart;
  unsigned __int16 totalSize;
  unsigned __int8 vertexCount;
  unsigned __int8 normalCount;
  unsigned __int8 compressionMode;
  unsigned __int8 padding[3];
  rw::math::vpu::Vector3 vertexArray[1];
};

/* 24583 */
struct rw::collision::ClusteredMeshCluster::Vertex16
{
  unsigned __int16 x;
  unsigned __int16 y;
  unsigned __int16 z;
};

/* 24584 */
struct rw::collision::ClusteredMeshCluster::Vertex32
{
  int x;
  int y;
  int z;
};

/* 24585 */
union rw::collision::ClusteredMeshCluster::CompressedVertexDataUnion
{
  rw::math::vpu::Vector3 *m_as_rwpmathVector3Ptr;
  rw::collision::ClusteredMeshCluster::Vertex32 *m_asVertex32Ptr;
  rw::collision::ClusteredMeshCluster::Vertex16 *m_asVertex16Ptr;
  int *m_asInt32Ptr;
};

/* 24586 */
struct __cppobj rw::collision::ClusteredMesh::ObjectDescriptor
{
  unsigned int m_maxClusters;
  unsigned int m_clusterDataSize;
  unsigned int m_numBranchNodes;
  unsigned int m_maxUnits;
  AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> m_bbox;
};

/* 24587 */
struct __cppobj rw::collision::ClusteredMeshUnit
{
  rw::collision::ClusteredMesh *mClusteredMesh;
  rw::collision::ClusteredMeshCluster *mCluster;
  unsigned __int8 *mUnitData;
};

/* 15594 */
struct __cppobj rw::math::vpu::MaskScalar
{
  __vector4 mV;
};

/* 24588 */
struct __cppobj rw::collision::TriangleQuery
{
  rw::math::vpu::Vector3 v0;
  rw::math::vpu::Vector3 v1;
  rw::math::vpu::Vector3 v2;
  rw::math::vpu::Vector3 triParam;
  rw::math::vpu::VecFloat lineParam;
  rw::math::vpu::Vector3 position;
  rw::math::vpu::MaskScalar intersects;
};

/* 30188 */
struct __cppobj __declspec(align(16)) rw::collision::rwc_FeatureIntersectionPrism
{
  rw::math::vpu::Vector3 m_ptsOn1[16];
  rw::math::vpu::Vector3 m_ptsOn2[16];
  rw::math::vpu::Vector3 normal;
  int m_numpts;
  unsigned int normalOverride;
};

/* 37442 */
union rw::collision::Mask4IntUnion
{
  __vector4 mask;
  int i[4];
};

/* 37443 */
struct __cppobj rw::collision::TriangleValidityCheckNodeData
{
  unsigned int parent;
  __declspec(align(16)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> bbox;
};

/* 37444 */
struct __cppobj rw::collision::ValidityCheckNodeData
{
  unsigned int parent;
  __declspec(align(16)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> bbox;
};

/* 37445 */
struct __cppobj rw::collision::KDTree::Traversal<rw::collision::ValidityCheckNodeData>::StackValue
{
  rw::collision::KDTree::NodeRef m_nodeRef;
  rw::collision::ValidityCheckNodeData m_data;
};

/* 37446 */
struct __cppobj __declspec(align(8)) rw::collision::KDTree::Traversal<rw::collision::ValidityCheckNodeData>
{
  const rw::collision::KDTree *m_kdtree;
  rw::collision::KDTree::Traversal<rw::collision::ValidityCheckNodeData>::StackValue m_stack[32];
  unsigned int m_top;
  rw::collision::KDTree::NodeRef m_cur;
};

/* 37447 */
struct __cppobj rw::collision::KDTree::Traversal<rw::collision::TriangleValidityCheckNodeData>::StackValue
{
  rw::collision::KDTree::NodeRef m_nodeRef;
  rw::collision::TriangleValidityCheckNodeData m_data;
};

/* 37448 */
struct __cppobj __declspec(align(8)) rw::collision::KDTree::Traversal<rw::collision::TriangleValidityCheckNodeData>
{
  const rw::collision::KDTree *m_kdtree;
  rw::collision::KDTree::Traversal<rw::collision::TriangleValidityCheckNodeData>::StackValue m_stack[32];
  unsigned int m_top;
  rw::collision::KDTree::NodeRef m_cur;
};

/* 37449 */
struct __cppobj rw::collision::ClusteredMeshValidityCheckNodeData
{
  unsigned int parent;
  __declspec(align(16)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> bbox;
};

/* 37450 */
struct __cppobj rw::collision::KDTree::Traversal<rw::collision::ClusteredMeshValidityCheckNodeData>::StackValue
{
  rw::collision::KDTree::NodeRef m_nodeRef;
  rw::collision::ClusteredMeshValidityCheckNodeData m_data;
};

/* 37451 */
struct __cppobj __declspec(align(8)) rw::collision::KDTree::Traversal<rw::collision::ClusteredMeshValidityCheckNodeData>
{
  const rw::collision::KDTree *m_kdtree;
  rw::collision::KDTree::Traversal<rw::collision::ClusteredMeshValidityCheckNodeData>::StackValue m_stack[32];
  unsigned int m_top;
  rw::collision::KDTree::NodeRef m_cur;
};

/* 37452 */
struct __cppobj rw::collision::DTreeValidityCheckNodeData
{
  unsigned int parent;
  __declspec(align(16)) AABBoxTemplate<rw::math::vpu::Matrix44Affine,rw::math::vpu::Vector3,rw::collision::AABBoxMemoryDumpPolicy> bb;
};

/* 37453 */
struct __cppobj rw::collision::KDTree::Traversal<rw::collision::DTreeValidityCheckNodeData>::StackValue
{
  rw::collision::KDTree::NodeRef m_nodeRef;
  rw::collision::DTreeValidityCheckNodeData m_data;
};

/* 37454 */
struct __cppobj __declspec(align(8)) rw::collision::KDTree::Traversal<rw::collision::DTreeValidityCheckNodeData>
{
  const rw::collision::KDTree *m_kdtree;
  rw::collision::KDTree::Traversal<rw::collision::DTreeValidityCheckNodeData>::StackValue m_stack[32];
  unsigned int m_top;
  rw::collision::KDTree::NodeRef m_cur;
};

/* 37455 */
struct __cppobj rw::collision::AllocationHelper
{
  unsigned int mem;
};

