/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'sk82_na_zd.xex'
*/

struct EA::Allocator::ICoreAllocator_vtbl;
struct rw::core::arena::ArenaTypeReg;
struct rw::core::arena::ArenaSectionTypes;
struct rw::core::arena::ArenaSectionExternalArenas;
struct rw::core::arena::ArenaSectionSubreferencesRecord;
struct rw::core::arena::ArenaSectionSubreferences;
struct rw::core::atom::StaticAtomTable::Members;
struct rw::core::atom::StaticAtomTable;
struct rw::IResourceAllocator;
struct rw::core::atom::DynamicAtomTable;
struct rw::core::atom::UnfixRefixAtoms;
struct rw::core::atom::UnfixRefixAtoms_vtbl;
struct rw::core::atom::FixupAtoms;
struct rw::core::atom::FixupAtoms_vtbl;
struct rw::core::arena::RefixCopyList::List;
struct rw::core::arena::ArenaIterator;
struct rw::core::arena::SizeAndAlignment;
struct rw::core::arena::ArenaSectionManifest;
struct rw::HashContainer<rw::PreallocatedBufferPolicy<rw::core::arena::ArenaIdMapHashTraits>,rw::core::arena::ArenaIdMapHashTraits>;
struct rw::core::arena::ArenaGroup;
struct rw::SeparateKeyAndDatumContained<unsigned int,rw::core::arena::Arena *>;
struct rw::core::arena::rw_ArenaTypeRegistry;
struct rw::core::arena::rw_NullArenaHolderType;
struct rw::core::arena::ArenaManagerData;
struct rw::core::arena::ArenaManager_vtbl;

/* 1132 */
enum rw::core::arena::AutoRefixEnum : __int32
{
  AUTO_REFIX_ENABLED = 0x0,
  AUTO_REFIX_DISABLED = 0x1,
};

/* 15526 */
struct rw::core::arena::ArenaFileHeaderMagicNumber
{
  unsigned __int8 prefix[4];
  unsigned __int8 body[4];
  unsigned __int8 suffix[4];
};

/* 15527 */
struct rw::core::arena::ArenaFileHeader
{
  rw::core::arena::ArenaFileHeaderMagicNumber magicNumber;
  unsigned __int8 isBigEndian;
  unsigned __int8 pointerSizeInBits;
  unsigned __int8 pointerAlignment;
  unsigned __int8 unused;
  unsigned __int8 majorVersion[4];
  unsigned __int8 minorVersion[4];
  unsigned int buildNo;
};

/* 15528 */
struct rw::core::arena::ArenaDictEntry
{
  void *ptr;
  void *reloc;
  unsigned int size;
  unsigned int align;
  unsigned int typeIndex;
  unsigned int typeId;
};

/* 15129 */
struct __cppobj rw::BaseResourceDescriptor
{
  unsigned int m_size;
  unsigned int m_alignment;
};

/* 15130 */
struct __cppobj rw::BaseResourceDescriptors<5>
{
  rw::BaseResourceDescriptor m_baseResourceDescriptors[5];
};

/* 15131 */
struct __cppobj rw::ResourceDescriptor : rw::BaseResourceDescriptors<5>
{
};

/* 15525 */
struct __cppobj rw::TargetResource
{
  void *m_baseResources[5];
};

/* 15529 */
struct __cppobj rw::core::arena::Arena
{
  rw::core::arena::ArenaFileHeader fileHeader;
  unsigned int id;
  unsigned int numEntries;
  unsigned int numUsed;
  unsigned int alignment;
  unsigned int virt;
  rw::core::arena::ArenaDictEntry *dictStart;
  rw::core::arena::ArenaSectionManifest *sections;
  void *base;
  rw::core::arena::SizeAndAlignment *m_unfixContext;
  rw::core::arena::ArenaIterator *m_fixContext;
  rw::ResourceDescriptor m_resourceDescriptor;
  rw::ResourceDescriptor m_resourcesUsed;
  rw::TargetResource m_resource;
  rw::core::arena::ArenaGroup *m_arenaGroup;
};

/* 15530 */
struct rw::core::arena::ArenaSection
{
  rw::core::arena::ArenaTypeReg *typeReg;
  unsigned int numEntries;
};

/* 15559 */
struct __cppobj rw::core::arena::ArenaSectionManifest : rw::core::arena::ArenaSection
{
  rw::core::arena::ArenaSection **dict;
};

/* 15557 */
struct __cppobj rw::core::arena::UnfixContextImpl
{
  rw::core::arena::Arena *m_arena;
  rw::core::arena::ArenaSectionTypes *m_types;
  rw::core::arena::ArenaSectionExternalArenas *m_externalArenas;
  rw::core::arena::ArenaSectionSubreferences *m_subrefs;
  rw::core::atom::DynamicAtomTable *m_unfixAtomTable;
  rw::core::atom::UnfixRefixAtoms *m_unfixAtomCallback;
  void *m_baseObjectPtr;
  rw::core::arena::ArenaIterator *iterator;
};

/* 15558 */
struct __cppobj rw::core::arena::SizeAndAlignment : rw::core::arena::UnfixContextImpl
{
  void *base;
  unsigned int size;
  unsigned int extraSize;
  unsigned int alignment;
};

/* 15545 */
struct __cppobj rw::core::arena::FixupContextImpl
{
  unsigned int *m_isFixupOk;
  const rw::core::atom::StaticAtomTable *m_fixupAtomTable;
  rw::core::atom::FixupAtoms *fixupAtomCallback;
};

/* 15546 */
struct rw::core::arena::rw_DebugWriteCBStruct
{
  unsigned int (__cdecl *m_writeCB)(void *, unsigned int, unsigned int);
  unsigned int (__cdecl *m_writeCBWithData)(void *, unsigned int, unsigned int, void *);
  void *m_writeCBData;
  unsigned int m_sizeWritten;
};

/* 15133 */
struct __cppobj rw::BaseResources<5>
{
  void *m_baseResources[5];
};

/* 15134 */
struct __cppobj rw::Resource : rw::BaseResources<5>
{
};

/* 15547 */
struct __cppobj rw::core::arena::RefixContextImpl
{
  rw::ResourceDescriptor m_alignmentRequirements;
  unsigned int (__cdecl *m_writeCB)(void *, unsigned int, unsigned int);
  unsigned int (__cdecl *m_writeCBWithData)(void *, unsigned int, unsigned int, void *);
  void *m_writeCBData;
  rw::core::arena::rw_DebugWriteCBStruct m_DebugCBStruct;
  rw::IResourceAllocator *m_refixStorageAllocator;
  rw::Resource m_refixStorage;
  rw::ResourceDescriptor m_refixStorageUsage;
  const rw::core::atom::DynamicAtomTable *m_refixAtomTable;
  rw::core::atom::UnfixRefixAtoms *m_refixAtomCallback;
  void *m_baseObjectPtr;
};

/* 15548 */
struct __cppobj rw::DeprecatedProxiedPtrType<rw::core::arena::Arena>
{
  rw::core::arena::Arena **m_forwardTo;
};

/* 15522 */
struct __cppobj rw::DeprecatedProxiedPtrType<void>
{
  void **m_forwardTo;
};

/* 15549 */
struct __cppobj rw::DeprecatedProxied<unsigned int>
{
  unsigned int *m_forwardTo;
};

/* 15550 */
struct __cppobj rw::DeprecatedProxied<unsigned int (__cdecl*)(void *,unsigned int,unsigned int)>
{
  unsigned int (__cdecl **m_forwardTo)(void *, unsigned int, unsigned int);
};

/* 15523 */
struct __cppobj rw::DeprecatedProxiedPtrType<unsigned int>
{
  unsigned int **m_forwardTo;
};

/* 15540 */
struct rw::core::atom::DynamicAtomTable
{
  rw::core::atom::StaticAtomTable **staticAtomTableArray;
  unsigned int numTables;
  rw::IResourceAllocator *allocator;
};

/* 15552 */
struct __cppobj rw::core::arena::RefixCopyList
{
  rw::core::arena::RefixCopyList::List *head;
  rw::core::arena::RefixCopyList::List *tail;
  rw::IResourceAllocator *allocator;
};

/* 15553 */
struct __cppobj rw::SimpleVector<rw::core::arena::ArenaSectionSubreferencesRecord>
{
  rw::IResourceAllocator *m_allocator;
  rw::Resource m_storage;
  rw::core::arena::ArenaSectionSubreferencesRecord *m_elements;
  unsigned int m_capacity;
  unsigned int m_size;
};

/* 15554 */
struct __cppobj rw::SimpleVector<rw::core::arena::ArenaDictEntry>
{
  rw::IResourceAllocator *m_allocator;
  rw::Resource m_storage;
  rw::core::arena::ArenaDictEntry *m_elements;
  unsigned int m_capacity;
  unsigned int m_size;
};

/* 15555 */
struct __cppobj rw::core::arena::DynamicArenaSubreferencesData
{
  rw::SimpleVector<rw::core::arena::ArenaSectionSubreferencesRecord> m_records;
  rw::SimpleVector<rw::core::arena::ArenaDictEntry> m_dict;
};

/* 15556 */
struct __cppobj rw::core::arena::ArenaIterator : rw::core::arena::FixupContextImpl, rw::core::arena::RefixContextImpl
{
  rw::core::arena::Arena *m_arena;
  void *offset;
  rw::DeprecatedProxiedPtrType<rw::core::arena::Arena> arena;
  rw::DeprecatedProxiedPtrType<void> origOffset;
  rw::DeprecatedProxiedPtrType<void> dictStart;
  rw::DeprecatedProxied<unsigned int> align;
  rw::DeprecatedProxied<unsigned int> dictEntry;
  rw::DeprecatedProxied<unsigned int (__cdecl*)(void *,unsigned int,unsigned int)> writeCB;
  rw::DeprecatedProxiedPtrType<unsigned int> isFixupOk;
  void *m_origOffset;
  void *m_dictStart;
  unsigned int m_align;
  unsigned int m_dictEntry;
  bool m_arenaLocalAtomTableAdded;
  rw::core::atom::DynamicAtomTable m_unfixRefixAtomTable;
  rw::core::atom::UnfixRefixAtoms *m_unfixRefixAtoms;
  rw::ResourceDescriptor m_resourceDescriptor;
  rw::IResourceAllocator *m_temporaryStorageAllocator;
  rw::core::arena::RefixCopyList m_autoRefixBlocks;
  rw::core::arena::DynamicArenaSubreferencesData m_subreferencesData;
  rw::Resource m_subreferencesResource;
};

/* 15562 */
struct __cppobj rw::core::arena::ArenaGroup
{
  rw::HashContainer<rw::PreallocatedBufferPolicy<rw::core::arena::ArenaIdMapHashTraits>,rw::core::arena::ArenaIdMapHashTraits> *m_ArenaIdMap;
};

/* 15531 */
struct __cppobj rw::core::arena::ArenaTypeReg
{
  unsigned int id;
  rw::core::arena::SizeAndAlignment *(__cdecl *unfixCB)(void *, rw::core::arena::SizeAndAlignment *);
  void (__cdecl *refixCB)(void *, void *, rw::core::arena::ArenaIterator *);
  unsigned int (__cdecl *fixupCB)(void *, rw::core::arena::ArenaIterator *);
  void (__cdecl *destructCB)(void *);
};

/* 15532 */
struct __cppobj __unaligned __declspec(align(4)) rw::core::arena::ArenaSectionTypes : rw::core::arena::ArenaSection
{
  rw::core::arena::ArenaTypeReg **dict;
};

/* 15533 */
struct __cppobj __unaligned __declspec(align(4)) rw::core::arena::ArenaSectionExternalArenas : rw::core::arena::ArenaSection
{
  rw::core::arena::ArenaDictEntry **dict;
};

/* 15535 */
struct __cppobj __unaligned __declspec(align(4)) rw::core::arena::ArenaSectionSubreferences : rw::core::arena::ArenaSection
{
  rw::core::arena::ArenaDictEntry *m_dictAfterRefix;
  rw::core::arena::ArenaSectionSubreferencesRecord *m_recordsAfterRefix;
  rw::core::arena::ArenaDictEntry *dict;
  rw::core::arena::ArenaSectionSubreferencesRecord *records;
  unsigned int numUsed;
};

/* 15541 */
struct __cppobj rw::core::atom::UnfixRefixAtoms
{
  rw::core::atom::UnfixRefixAtoms_vtbl *__vftable /*VFT*/;
};

/* 15537 */
struct rw::core::atom::StaticAtomTable
{
  rw::core::atom::StaticAtomTable::Members *table;
};

/* 15543 */
struct __cppobj rw::core::atom::FixupAtoms
{
  rw::core::atom::FixupAtoms_vtbl *__vftable /*VFT*/;
};

/* 14873 */
struct __cppobj EA::Allocator::ICoreAllocator
{
  EA::Allocator::ICoreAllocator_vtbl *__vftable /*VFT*/;
};

/* 15538 */
struct __cppobj rw::IResourceAllocator : EA::Allocator::ICoreAllocator
{
};

/* 15551 */
struct rw::core::arena::RefixCopyList::List
{
  unsigned int sizeInBytes;
  void *copy;
  void *key;
  rw::core::arena::RefixCopyList::List *next;
};

/* 15534 */
struct rw::core::arena::ArenaSectionSubreferencesRecord
{
  unsigned int objectId;
  unsigned int offset;
};

/* 15560 */
struct __cppobj rw::PreallocatedBufferPolicy<rw::core::arena::ArenaIdMapHashTraits>
{
  rw::SeparateKeyAndDatumContained<unsigned int,rw::core::arena::Arena *> *contents;
  unsigned int capacity;
};

/* 15561 */
struct __cppobj __unaligned __declspec(align(4)) rw::HashContainer<rw::PreallocatedBufferPolicy<rw::core::arena::ArenaIdMapHashTraits>,rw::core::arena::ArenaIdMapHashTraits> : rw::PreallocatedBufferPolicy<rw::core::arena::ArenaIdMapHashTraits>
{
  unsigned int size;
};

/* 15542 */
struct /*VFT*/ rw::core::atom::UnfixRefixAtoms_vtbl
{
  void (__cdecl *~UnfixRefixAtoms)(rw::core::atom::UnfixRefixAtoms *this);
  unsigned __int16 (__cdecl *At)(rw::core::atom::UnfixRefixAtoms *this, const void *, const char *);
  const char *(__cdecl *At)(rw::core::atom::UnfixRefixAtoms *this, const void *, unsigned __int16);
};

/* 15536 */
struct __declspec(align(4)) rw::core::atom::StaticAtomTable::Members
{
  char *atomNames;
  char *atomNameTail;
  unsigned int *stringIndex;
  unsigned __int16 *idArray;
  unsigned __int16 numAtomIDs;
  unsigned __int16 freeAtomIDs;
  unsigned __int16 nextAvailableID;
};

/* 15544 */
struct /*VFT*/ rw::core::atom::FixupAtoms_vtbl
{
  void (__cdecl *~FixupAtoms)(rw::core::atom::FixupAtoms *this);
  unsigned __int16 (__cdecl *At)(rw::core::atom::FixupAtoms *this, const char *);
};

/* 14874 */
struct /*VFT*/ EA::Allocator::ICoreAllocator_vtbl
{
  void (__cdecl *~ICoreAllocator)(EA::Allocator::ICoreAllocator *this);
  void *(__cdecl *Alloc)(EA::Allocator::ICoreAllocator *this, unsigned int, const char *, unsigned int, unsigned int, unsigned int);
  void *(__cdecl *Alloc)(EA::Allocator::ICoreAllocator *this, unsigned int, const char *, unsigned int);
  void (__cdecl *Free)(EA::Allocator::ICoreAllocator *this, void *, unsigned int);
};

/* 15563 */
struct __cppobj rw::SeparateKeyAndDatumContained<unsigned int,rw::core::arena::Arena *>
{
  unsigned int key;
  rw::core::arena::Arena *data;
};

/* 15564 */
struct __cppobj rw::core::arena::ArenaIdMapHashTraits
{
};

/* 15647 */
struct rw::core::arena::rw_ArenaTypeRegHeader
{
  unsigned int numEntries;
  unsigned int numUsed;
};

/* 15648 */
struct __cppobj rw::core::arena::ArenaManager
{
  rw::core::arena::ArenaManager_vtbl *__vftable /*VFT*/;
};

/* 15654 */
struct /*VFT*/ rw::core::arena::ArenaManager_vtbl
{
  void (__cdecl *~ArenaManager)(rw::core::arena::ArenaManager *this);
  rw::core::arena::ArenaManagerData *(__cdecl *Data)(rw::core::arena::ArenaManager *this);
};

/* 15653 */
struct __cppobj rw::core::arena::ArenaManagerData
{
  rw::core::arena::rw_ArenaTypeRegistry *m_typeRegistry;
  rw::core::arena::ArenaGroup m_ArenaGroup;
  unsigned __int8 m_NullArena[1024];
  rw::core::arena::rw_NullArenaHolderType *m_NullArenaHolder;
  unsigned int m_isOpen;
};

/* 15649 */
struct __cppobj rw::core::arena::rw_ArenaTypeRegistry
{
  rw::core::arena::rw_ArenaTypeRegHeader header;
  rw::core::arena::ArenaTypeReg record[1];
};

/* 15650 */
struct __cppobj rw::core::arena::ArenaSectionAtoms : rw::core::arena::ArenaSection
{
  rw::core::atom::StaticAtomTable *atomTable;
};

/* 15651 */
struct rw::core::arena::rw_NullSections
{
  rw::core::arena::ArenaSectionManifest manifest;
  rw::core::arena::ArenaSection *additionalSectionPtrs[4];
  rw::core::arena::ArenaSectionTypes types;
  rw::core::arena::ArenaTypeReg *typesPtrs[6];
  rw::core::arena::ArenaSectionExternalArenas extArenas;
  rw::core::arena::Arena *extArenaRecord[3];
  rw::core::arena::Arena *extArenaPtrs[3];
  rw::core::arena::ArenaSectionSubreferences subrefs;
  rw::core::arena::ArenaSectionAtoms atoms;
};

/* 15652 */
struct __cppobj rw::core::arena::rw_NullArenaHolderType
{
  rw::core::arena::Arena arena;
  rw::core::arena::rw_NullSections sections;
  rw::core::arena::ArenaDictEntry entry;
};

/* 15655 */
struct __cppobj rw::core::arena::ArenaGroupHolder
{
  rw::SeparateKeyAndDatumContained<unsigned int,rw::core::arena::Arena *> *m_buffer;
  rw::core::arena::ArenaGroup *m_arenaGroup;
};

/* 15656 */
struct __cppobj rw::core::arena::TypeStaticMetadata
{
  const char *m_name;
};

/* 15657 */
struct __cppobj rw::core::arena::TypeStaticMetadata::ConstIterator
{
  rw::core::arena::TypeStaticMetadata m_data;
};

/* 15658 */
struct __cppobj rw::core::arena::ArenaExportedObject
{
  unsigned int typeId;
  void *ptr;
  rw::Resource resource;
  rw::ResourceDescriptor resourceDescriptor;
};

/* 1016 */
enum EA::Serialization::archivestate : __int32
{
  goodstate = 0x0,
  eofbit = 0x1,
  failbit = 0x2,
  badbit = 0x4,
  statemask = 0x7,
};

/* 16680 */
struct __cppobj EA::Serialization::BaseArchive<rw::core::arena::basic_fixup_archive<EA::Serialization::Endian::InPlaceNativeEndianConverter> >
{
  EA::Serialization::archivestate mState;
};

/* 16681 */
struct __cppobj EA::Serialization::BaseIArchive<rw::core::arena::basic_fixup_archive<EA::Serialization::Endian::InPlaceNativeEndianConverter> > : EA::Serialization::BaseArchive<rw::core::arena::basic_fixup_archive<EA::Serialization::Endian::InPlaceNativeEndianConverter> >
{
};

/* 16708 */
struct __cppobj rw::core::arena::basic_fixup_archive<EA::Serialization::Endian::InPlaceNativeEndianConverter> : EA::Serialization::BaseIArchive<rw::core::arena::basic_fixup_archive<EA::Serialization::Endian::InPlaceNativeEndianConverter> >
{
  void *mBase;
  rw::core::arena::Arena *mArena;
};

/* 16719 */
struct __cppobj rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter>::UnfixedCopy
{
  rw::IResourceAllocator *allocator;
  unsigned __int8 *allocatedMemory;
  void *base;
  void *originalObject;
  unsigned int sizeInBytes;
};

/* 16701 */
struct __cppobj EA::Serialization::BaseArchive<rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter> >
{
  EA::Serialization::archivestate mState;
};

/* 16702 */
struct __cppobj EA::Serialization::BaseOArchive<rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter> > : EA::Serialization::BaseArchive<rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter> >
{
};

/* 16720 */
struct __cppobj rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter> : EA::Serialization::BaseOArchive<rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter> >
{
  bool mAutoRefix;
  rw::core::arena::Arena *mArena;
  rw::core::arena::ArenaIterator *mIterator;
  void *const mPtr;
  unsigned int mMaximumSize;
  const unsigned __int8 *mHighWaterMark;
  bool mClosed;
  unsigned int mMemoryType;
  rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter>::UnfixedCopy mUnfixedCopy;
  rw::core::arena::basic_unfix_archive<EA::Serialization::Endian::NativeEndianConverter>::UnfixedCopy mOriginal;
};

/* 20801 */
struct __cppobj rw::core::arena::basic_refix_archive<EA::Serialization::Endian::InPlaceNativeEndianConverter> : rw::core::arena::basic_fixup_archive<EA::Serialization::Endian::InPlaceNativeEndianConverter>
{
};

/* 37592 */
struct __cppobj rw::core::arena::ArenaReaderFromMemoryResource
{
  void *m_resource;
  rw::BaseResourceDescriptor m_descriptor;
  unsigned int m_pos;
};

/* 38164 */
struct __cppobj rw::core::arena::Adder
{
  rw::core::arena::ArenaDictEntry *m_entry;
  unsigned int *m_index;
  rw::core::arena::ArenaDictEntry *m_endEntry;
  unsigned int m_lastIndex;
};

/* 38165 */
struct __cppobj rw::core::arena::DefaultRuntimeAtomFixup : rw::core::atom::FixupAtoms
{
};

/* 38166 */
struct /*VFT*/ rw::core::arena::DefaultRuntimeAtomFixup_vtbl
{
  void (__cdecl *~FixupAtoms)(rw::core::atom::FixupAtoms *this);
  unsigned __int16 (__cdecl *At)(rw::core::atom::FixupAtoms *this, const char *);
};

/* 38167 */
struct __cppobj rw::core::arena::DefaultRuntimeUnfixRefixAtoms : rw::core::atom::UnfixRefixAtoms
{
};

/* 38168 */
struct /*VFT*/ rw::core::arena::DefaultRuntimeUnfixRefixAtoms_vtbl
{
  void (__cdecl *~UnfixRefixAtoms)(rw::core::atom::UnfixRefixAtoms *this);
  unsigned __int16 (__cdecl *At)(rw::core::atom::UnfixRefixAtoms *this, const void *, const char *);
  const char *(__cdecl *At)(rw::core::atom::UnfixRefixAtoms *this, const void *, unsigned __int16);
};

