// (c) Electronic Arts. All Rights Reserved.
#ifndef RWCOLLISION_VOLUMES_RW_COLLISION_DEPRECATED_LINECAPSULE_H
#define RWCOLLISION_VOLUMES_RW_COLLISION_DEPRECATED_LINECAPSULE_H

#include "rw/collision/deprecated/linecylinder.h"

#endif //!RWCOLLISION_VOLUMES_RW_COLLISION_DEPRECATED_LINECAPSULE_H
